### ISSUE TITLE
Check spelling with only english language available

### ISSUE THREAD

**Issue by Truleu** [zen-browser/desktop#1092]
### What happened?

The `Check Spelling` functionality shows only English language option even after downloading other language dictionaries

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by flyri0** [comment]
I'm experiencing the same issue, and it's quite inconvenient. Any updates on a fix?

**Comment by luisfscoelho** [comment]
I'm with the same issue too.

**Comment by yotamguttman** [comment]
same issue here as @Jwakers. [I asked on Reddit](https://www.reddit.com/r/zen_browser/s/KCkwbT1E0T) and someone replied that they're also experiencing that. 
![image](https://github.com/user-attachments/assets/7e389859-994f-4259-a7cd-48ed29b35cf8)

what I found is that just most words in GB eng spellng are flagged and some others aren't which is weird. it's like BG Eng spell checking is half way implemented.

anyways, no reaction from the devs at all about this issue?

**Comment by flyri0** [comment]
I found the problem. When you go to [Dictionaries and Language Packs](https://addons.mozilla.org/en-US/firefox/language-tools/), what you need to install is a dictionary, not a language pack. In my case, which is Portuguese.

![image](https://github.com/user-attachments/assets/d9f7fc88-4180-44a5-b00b-1f6ab3b0c0fa)

I have one language pack option and three dictionary options. Once I installed a dictionary, the option for Portuguese appeared.

![image](https://github.com/user-attachments/assets/434c0735-f362-4b98-8898-59fa1595013a)

**Comment by luisfscoelho** [comment]
> I found the problem. When you go to [Dictionaries and Language Packs](https://addons.mozilla.org/en-US/firefox/language-tools/), what you need to install is a dictionary, not a language pack. In my case, which is Portuguese.
> 
> ![image](https://private-user-images.githubusercontent.com/64603958/376040751-d9f7fc88-4180-44a5-b00b-1f6ab3b0c0fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDY5MDUsIm5iZiI6MTcyODg0NjYwNSwicGF0aCI6Ii82NDYwMzk1OC8zNzYwNDA3NTEtZDlmN2ZjODgtNDE4MC00NGE1LWIwMGItMWY2YWIzYjBjMGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDE5MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOTk1OGM2Mjc5Y2ViOThlNmFiODQ5MzE1NTgzMDAzYTFmOTBmMjAxZGRjMzIwODA3ZDYzOWY5MmNkZDJlY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X929zFv2-gpwLiHY0BgdvydKsCNCRrG62G81IYhPsv8)
> 
> I have one language pack option and three dictionary options. Once I installed a dictionary, the option for Portuguese appeared.
> 
> ![image](https://private-user-images.githubusercontent.com/64603958/376040766-434c0735-f362-4b98-8898-59fa1595013a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDY5MDUsIm5iZiI6MTcyODg0NjYwNSwicGF0aCI6Ii82NDYwMzk1OC8zNzYwNDA3NjYtNDM0YzA3MzUtZjM2Mi00Yjk4LTg4OTgtNTlmYTE1OTUwMTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDE5MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjODhmMmYyMmNmZWY0NWJiM2I4ZGE5ZGY4NmRiNTYxYmQwM2NiMzBkMjliZDE5ZWU3ODkzMDRkMWU4ZjZmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jwt-hGuVAwo-FywniEVnb9GCqf8T5O0g7RL1_NEKCcg)

It works for me.

**Comment by ingepettersen** [comment]
I'm unable to install new dictionaries at all. When clicking the "Add to Firefox" button on one in https://addons.mozilla.org/ it never installs, and I just get a "bouncing" install button forever... Flatpak version of Zen Browser, if that matters.

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting this on the lastest version? (a17 as of this comment) Or are you still unable to install a new dictionary?

**Comment by ingepettersen** [comment]
It works for me now...

**Comment by filip-van-hoeckel** [comment]
Works for me as well.

**Comment by yotamguttman** [comment]
I still have the problem. but I haven't tried to install another dictionary. I didn't quite get it, is this the actual solution? I should install a British English dictionary from the Mozilla addons store?

**Comment by flyri0** [comment]
As mentioned in the [official Mozilla documentation](https://addons.mozilla.org/en-US/firefox/language-tools/), 'Installing a dictionary add-on will add a new language option to your spell checker, enabling it to check your spelling as you type in Firefox.'

So, yes, this is indeed the solution.

**Comment by yotamguttman** [comment]
okay thanks @flyri0. please correct me if I'm wrong but the article you linked doesn't cover how to (if necessary) configure a new spell-checker language pack. I've installed the correct pack and can see it in my extensions page, but how do I set it to be my default spell checker? because the browser is currently still correcting my text according to the American spelling.

I tired searching for 'spell-checker' and 'dictionary' in Zen's settings but nothing came up.
![image](https://github.com/user-attachments/assets/7bc149d0-9c4b-4f3d-ac0c-03fe04a6c0a7)
![image](https://github.com/user-attachments/assets/32f85440-357e-40e4-bb8d-e6da70a79fce)

**Comment by flyri0** [comment]
@yotamguttman you need to right-click on a text field, then in the menu that opens, go to "Languages."

![376040766-434c0735-f362-4b98-8898-59fa1595013a.png](https://github.com/user-attachments/assets/03bc94da-8024-4fd7-850e-18968ffe2431)

**Comment by yotamguttman** [comment]
oh right! I've found the sub menu but it only shows US English:
![image](https://github.com/user-attachments/assets/830592fe-b849-4433-9039-c38a19eaaabe)

even though I have the Eng GB dictionary installed, following the guide above:
![image](https://github.com/user-attachments/assets/c3d3f836-c5fc-43a7-8acb-409a004bcda0)
![image](https://github.com/user-attachments/assets/f8e3fd6a-798f-4391-a3c0-74fa8c9bda32)


any idea why?

**Comment by flyri0** [comment]
You installed a language pack, not a [dictionary](https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-gb/).

![061120241057212747](https://github.com/user-attachments/assets/69fa66d1-da20-4f97-bd51-dd8858a28e16)

**Comment by salamijason** [comment]
Looks like there is a solution to this issue. 

Please continue to help the user figure out the dictionaries.

In the meantime though, I will close this issue since we're trying to keep our roadmap clean. Thank you lots!

**Comment by yotamguttman** [comment]
I agree that there's a solution and the issue can be closed. but the method of adding dictionaries is so fiddly and unintuitive. I guess it's Firefox fault but I can see how many more Zen users will get stuck on it. ideally it should become so much simpler. 

the fact that you open the settings and there you see this:
![383477480-7bc149d0-9c4b-4f3d-ac0c-03fe04a6c0a7](https://github.com/user-attachments/assets/1a97c066-129c-4cf0-853a-b1aac6048b33)
is even more confusing! 
there's absolutely no mentioning for a solution for adding a dictionary, even within the relevant section in the settings. had you not sent the article above and explained to me how to work this out individually, I'd still be lost.

**Comment by salamijason** [comment]
I get what you mean and I do agree that it should be easier for the user. But since it's a Firefox issue as well as something not currently being focused on by the devs, it is unlikely they'll add anything significant such as a feature. I'll pass on word to maybe add a line that talks about dictionaries.

Further, since this is a base Firefox feature, it might be futile to add a solution since Firefox has recently been making a lot of changes through their patches and is predicted to change more in the near future. 

Everytime one of these patches are released, the devs have to spend a lot of time going through every changed line of code to make Zen work again as it should. Changing base Firefox functionality is just not viable at this moment in time. 

But still, I'm now capable of helping any other user that may run into this issue so I hope that, at least, will control the issue a little. I'll also be sharing the links and instructions to the rest of the issue handling team.

Thank you all for pointing this out.

**Comment by yotamguttman** [comment]
the only thing I can suggest as a workaround is having a clearer article about it in Zen's documentations. because honestly, it's not such a difficult issue to fix but the way Firefox handled its article is just quite confusing. Zen can just explain it clearer than Firefox does and users would easily be able to workout for themselves
