### ISSUE TITLE
Bad round corners pixels

### ISSUE THREAD

**Issue by Mojas84** [zen-browser/desktop#1128]
### What happened?

In colored theme i see this rounded corners very bad pixelated...... https://screenshotx.com/i/tsc6p8
2. https://screenshotx.com/i/dr94xb

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.34

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by Mojas84** [comment]
Maybe but maybe not with red color Catpuccin Latte is pixels more visible....

**Comment by amjido-01** [comment]
can i work on this?

**Comment by mauro-balades** [comment]
> can i work on this?

sure!

**Comment by LeMoonStar** [comment]
Hey! The default themes have since been changed significantly and I cannot seem to find any pixelated corners anymore. I will close this issue for now, as it is likely not a problem anymore. This is further supported by this issue being stale for almost two months by now.

If this issue is still, in fact, a thing, please comment or re-open it.
