### ISSUE TITLE
Chinese title typography error

### ISSUE THREAD

**Issue by Eff0rtly** [zen-browser/desktop#1191]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

![QQ截图20240903191311](https://github.com/user-attachments/assets/996578b7-c18c-4c92-b538-d6b300075b09)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
no log
```

**Comment by Eff0rtly** [comment]
The text is too close to the icon

**Comment by me66ccff** [comment]
Yes, I also met this error, this browser also has a disadvantage in the promotion of China's point is that the localization is not yet perfect, I'm empty to find out if there can be in the localization of this area to help.

**Comment by i1hwan** [comment]
It seems like this issue is not limited to Chinese but also occurs in other languages, such as Korean. I suspect this might be a problem when using Zen Browser with languages other than English. For instance, if you change the language setting of the Korean Zen Browser to English and restart it, the missing space between the favicon and website title is correctly displayed.

![zen_989PmkPa82U](https://github.com/user-attachments/assets/4d01e247-03bd-4b2a-abbe-674670f40b0c)
**When the Zen Browser is set to the Korean language**
![zen_sZqvOCndSmC](https://github.com/user-attachments/assets/08a38cd0-c4ce-4d08-83c8-0e3b0fda0dca)
**After changing the language setting of Zen Browser to English and restarting it**

**Comment by mauro-balades** [comment]
Does it also happen with firefox?

**Comment by i1hwan** [comment]
> Does it also happen with firefox?

Unlike Zen, Firefox does not support vertical tabs, so a direct comparison is not feasible. However, I checked it on Firefox version 130.

![firefox_CR1AGAv82w](https://github.com/user-attachments/assets/821284e5-039f-41b0-8d1b-6428b534b8b4)
When the Firefox is set to the Korean language
![firefox_OH4ZPnDNN4](https://github.com/user-attachments/assets/94812d7b-0f3e-4595-8a52-f4cb8f80bacf)
After changing the language setting of Firefox to English and restarting it

It seems that, at least from Firefox's perspective, there are no issues.

**Comment by LeMoonStar** [comment]
Testing in the current Zen version (1.0.1-a.17) I cannot reproduce this issue. As this issue has been stale for quite a while, it seems safe to assume it has been fixed.
If the issue still persist, please comment or re-open this issue.

![image](https://github.com/user-attachments/assets/57a716ae-8b9a-4d05-96c2-fe7712aa3eb7)
