### ISSUE TITLE
Automatically select search/ url bar when opening Zen

### ISSUE THREAD

**Issue by bengiv** [zen-browser/desktop#120]
When opening Firefox the search/ url bar is automatically selected means you can just open Firefox and start searching something or openeing a web page, would greatly appreciate if Zen could also adapt that

**Comment by mauro-balades** [comment]
Im not gonna implement this because it will automatically focus the URL, making it expand. It becomes annoying, sorry.

Maybe in the future if I manage to make it not open up

**Comment by ntnguyen1234** [comment]
@mauro-balades I think it's not about focus and expand, but in Firefox it just focus with a ring like this

![image](https://github.com/user-attachments/assets/4f47457c-0b74-4334-a1e8-d16fd875df3f)

Similar to when pressing `Ctrl + T` in Zen to open new tab and the cursor is automatically in the URL bar

![image](https://github.com/user-attachments/assets/2bcdb005-dcf9-4a2b-ac35-973c68c5afc0)

I'm not sure why the behavior when launching and opening new tab has this only difference. I tried searching many configurations in `about:config` but not success yet.

**Comment by bengiv** [comment]
yea thats what i mean

**Comment by mayank99** [comment]
I honestly thought it was a bug that the url bar does not get focused when a window is opened.

@mauro-balades 

> it will automatically focus the URL

This is kinda the point. The url bar gets focused so that you can start typing right away. This is particularly important because opening a new window (<kbd>cmd/ctrl</kbd> + <kbd>N</kbd>) currently has different behavior from opening a new tab in the same window.

> …making it expand. It becomes annoying, sorry. Maybe in the future if I manage to make it not open up

Is this only a problem for the floating/compact-style url bars? By default, the url bar doesn't "expand"; it's just always there. So maybe this focus could be set only for the default url bar?

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/890

 ~ This is an automatic operation to better enhancements requests organization.
