### ISSUE TITLE
Website data is shared across workspaces

### ISSUE THREAD

**Issue by lumpysimon** [zen-browser/desktop#1239]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

My understanding of workspaces (as an Arc user) is that they are completely separate from each other with no data, cookies, history, extensions, etc, shared between them. This (in my opinion) is what makes them so incredibly useful.

In Zen, if I open for example mail.google.com in one workspace and sign in, then open it in a different workspace, I am signed into the Google account from the first workspace.

And when I type in the address bar in one workspace, I see suggestions from tabs/history/etc from other workspaces.

So it looks as if all website data, such as cookies, and browser data such as history, extensions, etc, are shared between workspaces.

Is this expected behaviour, or a bug, or because workspaces are still a beta feature?

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by HiroDane** [comment]
I had the same confusion. I later found out that Mozilla has made an official extension called "Multi-Account Containers" to implement this, and I an currently using that in zen. 

I believe the zen "workspaces" are just a visual separation to keep tabs organized instead of having a (suppose) 100+ tabs open one after another. In its current form its not meant to do a containers job.

Although the extension works fairly well, It would be cool to have it integrated into zen directly somehow.

**Comment by Kaedriz** [comment]
I think you are confusing the aspect of different "profiles" rather than workspaces. As a Vivaldi user for some time, in Zen they are kinda similar. Essentially they act as your "folders" which you need at a time. You can have your workspace with music only, shopping etc.

In the future, you could do this separation of data by different profiles, even Firefox is working on something like this I think.

For the majority of users, data separation of workspaces would just cause much more issues like this one, just inverted. But I don't know where dev intention of workspaces lays.

**Comment by Truleu** [comment]
There's no confusion, in Arc workspaces has this separation and it works quite well. I don't think it would cause any issue at all for the majority of users since they have to create the workspace themselves. 

You shouldn't have to open another window on another profile to have this separation

> I think you are confusing the aspect of different "profiles" rather than workspaces. As a Vivaldi user for some time, in Zen they are kinda similar. Essentially they act as your "folders" which you need at a time. You can have your workspace with music only, shopping etc.
> 
> In the future, you could do this separation of data by different profiles, even Firefox is working on something like this I think.
> 
> For the majority of users, data separation of workspaces would just cause much more issues like this one, just inverted. But I don't know where dev intention of workspaces lays.

**Comment by Anthonyy232** [comment]
I'm not sure about Arc on MacOS, but it certainly doesn't have this separation in Arc on Windows (which I do want). Currently in Arc on Windows, spaces share the same website data, and also the search suggestion is the same between profiles.. which I loathe.

**Comment by kvnxiao** [comment]
@Anthonyy232 That is because you have to set the profile associated with a workspace in Arc (on both Mac and Windows).

Just want to clarify nomenclature from Arc Browser:
- Space: browsing separation --> think tab grouping or tab folders
- Profile: the data, cookies, history, etc. associated with a Space

Any space in Arc can share the same profile between each other so that browsing history, cookies, login info, etc. are available; or alternatively spaces can have entirely different profiles with their own browsing data.

**Comment by Anthonyy232** [comment]
Did not know that, thanks!

**Comment by lumpysimon** [comment]
@kvnxiao Ah yes, you are correct - in Arc I have multiple profiles, with each space being associated with a profile (I'd forgotten there was this extra step).

**Comment by Anthonyy232** [comment]
I agree -- make it a choice. Choice is good!

**Comment by penkin** [comment]
Does anyone know if there is a way to make the profiles not open new windows?

**Comment by Truleu** [comment]
There isn't yet. We're waiting for it to be possible to bind profiles to workspaces. Or at least bind containers to workspaces, this would works just fine

**Comment by NOCanoa** [comment]
I will mark this as low prio, but next time enhancements in discussions pls

**Comment by japboy** [comment]
There is a discussion related to this topic (which is transferred from issue #500)

- https://github.com/zen-browser/desktop/discussions/818

**Comment by mauro-balades** [comment]
Workspaces are for organization, not containerization. Sure, I could see into how to make profiles not open in a new windows, ill discuss it internally, see what we can do. Ill close this issue and open a new one about the profiles.

**Comment by vatsalraicha** [comment]
Then Zen is just a wrapper to make it look like Arc.
The beauty of Arc is Spaces and Profiles can be linked or delinked and works seamlessly once u set up a space.
Disappointed in Zen.

**Comment by pranavgoel29** [comment]
> [@Anthonyy232](https://github.com/Anthonyy232) That is because you have to set the profile associated with a workspace in Arc (on both Mac and Windows).
> 
> Just want to clarify nomenclature from Arc Browser:
> 
> * Space: browsing separation --> think tab grouping or tab folders
> * Profile: the data, cookies, history, etc. associated with a Space
> 
> Any space in Arc can share the same profile between each other so that browsing history, cookies, login info, etc. are available; or alternatively spaces can have entirely different profiles with their own browsing data.

Hope this comes to Zen

**Comment by SaidBahaDev** [comment]
> Then Zen is just a wrapper to make it look like Arc. The beauty of Arc is Spaces and Profiles can be linked or delinked and works seamlessly once u set up a space. Disappointed in Zen.

It’s what made Arc a killer feature, and the worst part is it’s marked as low priority , instead of listening to what real users think.

**Comment by Kaedriz** [comment]
> > Then Zen is just a wrapper to make it look like Arc. The beauty of Arc is Spaces and Profiles can be linked or delinked and works seamlessly once u set up a space. Disappointed in Zen.
> 
> It’s what made Arc a killer feature, and the worst part is it’s marked as low priority , instead of listening to what **_real users_** think.

I don't know what's stopping you from just using Arc, than bitching on other github's, forcing it to *your* way. Majority of *real users* don't think this is that much important, aside from vocal minority about productivity bla bla, so it's low priority. Period.
I, for one, don't like some things Zen implemented, but I'm not complaining here about it.

**Comment by SaidBahaDev** [comment]
> > > Then Zen is just a wrapper to make it look like Arc. The beauty of Arc is Spaces and Profiles can be linked or delinked and works seamlessly once u set up a space. Disappointed in Zen.
> > 
> > 
> > It’s what made Arc a killer feature, and the worst part is it’s marked as low priority , instead of listening to what **_real users_** think.
> 
> I don't know what's stopping you from just using Arc, than bitching on other github's, forcing it to _your_ way. Majority of _real users_ don't think this is that much important, aside from vocal minority about productivity bla bla, so it's low priority. Period. I, for one, don't like some things Zen implemented, but I'm not complaining here about it.

First of all, I wasn’t addressing you directly, and your comment isn’t helpful. If you don’t agree with the feedback, you’re free to ignore it instead of dismissing others’ concerns. Different users have different needs, and just because something isn’t important to you doesn’t mean it’s irrelevant. If you have nothing constructive to add, there’s no need to engage, this kind of comments only come from B* like you ;)

**Comment by HarshalGunjalOp** [comment]
> > Then Zen is just a wrapper to make it look like Arc. The beauty of Arc is Spaces and Profiles can be linked or delinked and works seamlessly once u set up a space. Disappointed in Zen.
> 
> It’s what made Arc a killer feature, and the worst part is it’s marked as low priority , instead of listening to what real users think.

I completely agree. This should definitely not be low priority. I think the idea of different workspace different profile should be an in-built option in zen. I'm not saying to make it default, just make it and option to opt-in or out of, so that the people who want this feature can just opt in for that. I know 6 of my 7 friends who refused to use zen just because even though the tabs can be containerized and have different profiles, the history is still same across, and that made navigation through history really difficult.

Also for those saying that for different profiles we can just use the about:profiles, I'm sure you know how janky that thing is. The first time I used it I literally shifted back to arc just because I can't go through the hassle of going to a different website just to change my profile. It was a miracle I discovered containers and decided to stay. Now I love this browser except for the fact that the different profiles somehow share the same history.

**Comment by georgekatsanos-nc** [comment]
we're two users coming from Arc and we just realized workspaces share the same sessions (e.g. google) so we're actually need to move to a different browser asap as we use different google profiles for work / personal so basically this is unusable for us.

**Comment by penkin** [comment]
> we're two users coming from Arc and we just realized workspaces share the same sessions (e.g. google) so we're actually need to move to a different browser asap as we use different google profiles for work / personal so basically this is unusable for us.

I'm pretty sure this works now @georgekatsanos-nc. I am still on Arc but playing with Zen. Basically just waiting for folders and smart folders :)

What I see though is you can have workspaces and containers linked to those workspaces with all your accounts separate. https://docs.zen-browser.app/user-manual/workspaces

**Comment by georgekatsanos-nc** [comment]
Indeed, I needed to enable separate essentials per container in the settings 

![Image](https://github.com/user-attachments/assets/46451188-aa0d-4b40-9bc1-6d2f4019289c) and then set default container per workspace (personal/work). Seems to work.

**Comment by mathdenduper** [comment]
> I had the same confusion. I later found out that Mozilla has made an official extension called "Multi-Account Containers" to implement this, and I an currently using that in zen.
> 
> I believe the zen "workspaces" are just a visual separation to keep tabs organized instead of having a (suppose) 100+ tabs open one after another. In its current form its not meant to do a containers job.
> 
> Although the extension works fairly well, It would be cool to have it integrated into zen directly somehow.

@HiroDane Hey, how did you get this extension to work? I've installed this extension, but containers still share browsing history, website data, extensions, etc. Much help appreciated.
