### ISSUE TITLE
Migrate Homebrew Cask to a separate repository

### ISSUE THREAD

**Issue by AlternateRT** [zen-browser/desktop#1274]
Right now, the Homebrew Cask for Zen is being hosted directly inside the `zen-browser/desktop` repository; **this is not ideal**. It should be moved to a separate repository, ideally `zen-browser/homebrew-browser` to keep things mostly the same.

### Rationale
The way things currently works means that whenever anyone runs:
```
brew tap zen-browser/browser https://github.com/zen-browser/desktop.git
```

they are _unwittingly cloning the **entire** `zen-browser/desktop` repository_. This is not how Homebrew is supposed to work.

[Third-party repositories for Homebrew Casks](https://docs.brew.sh/Taps) (or simply Taps) are only meant to host the cask you want Homebrew to track, update, and install for you (in the case for Zen, that cask is only `zen-browser`).

In addition, if the `Casks/zen-browser.rb` file were to be moved to a dedicated repository, everyone would benefit of being [able to use the one-argument form of `brew tap`](https://docs.brew.sh/Taps#repository-naming-conventions-and-assumptions). So the command from above would instead become:
```
brew tap zen-browser/browser
```

**Comment by HarryHeres** [comment]
Good observation! I just want to clarify some things why we haven't done this yet. We are aware of the fact that the tapping is cloning the whole repo at the moment. On the other hand, this was the fastest solution to enable our MacOS users to be able to use the browser since the manual installation process is still not ideal (but being worked on). Also, there wasn't much time to create and setup a whole new repo just for homebrew as there were lots of important features that needed to be prioritized.

**Comment by Vfposselt** [comment]
Thanks for the heads up! Do you have an estimated timeline for when ‘brew install --cask zen’ will be available?

**Comment by HarryHeres** [comment]
> Thanks for the heads up! Do you have an estimated timeline for when ‘brew install --cask zen’ will be available?

We are figuring out the app signing and notarization process. That is one of the requirement for Zen to be able to pushed to the official Homebrew repo. I will have to talk to Mauro about this, so I cannot give you an exact estimate right now, but it is on our radar. I'd expect a month maybe?
