### ISSUE TITLE
Unable to middle click the empty space for a new tab

### ISSUE THREAD

**Issue by JoseBritto** [zen-browser/desktop#1354]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Before the version that changed the new tab button to the top instead of bottom I could middle click the empty space to create a new tab. This was really convenient how it works in Firefox.

Now the only place middle-click works is the new tab button which is pointless.

I am not sure if this is related to the position of the new tab button. If it is, I really preferred the old positioning.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

Linux

**Comment by Ansis100** [comment]
I keep trying to open a new tab this way because of muscle memory. Would very much like to see this implemented.

**Comment by ekorchmar** [comment]
For anyone looking to tackle this, here is the relevant code in Firefox:
https://github.com/mozilla/gecko-dev/blob/3f193a8bb0759058c2f9a9d7761ad73bc6ffd4b1/browser/components/tabbrowser/content/tabbrowser.js#L4641

Making it work with the element #TabsToolbar should fix the problem. If there are no unforseen interactions with Workspaces model.

**Comment by ekorchmar** [comment]
https://github.com/mozilla/gecko-dev/blob/6bb5daea3d7ef0f8e02294963df6a012b91c5b78/browser/components/tabbrowser/content/tabs.js#L364

This seems very convoluted in Firefox. It looks like middle click (line 364) is only causing a tab to appear if:
1. No tab is in the way (L366)
2. Scrollbox is exactly the element that got clicked (L377) -- and Zen browser does not seem to use it in it's custom tab bar.

My naiive approach would be to patch this file to look for `tabbrowser-tabs` as closest element instead of `scrollbox`, but I am not familiar with how patching workflow is setup in Zen, and can not really feasibly rebuild Zen on my machine. I also can not guarantee that this will fix the issue.

**Comment by sjclayton** [comment]
@JoseBritto 

This functionality has been implemented as of Zen 1.0.1-a.8, this issue can be closed.

**Comment by JoseBritto** [comment]
Amazing. Middle click now works. Thanks everyone who worked on this :heart:
