### ISSUE TITLE
tabs become ghosts when one is moved to a new workspace

### ISSUE THREAD

**Issue by unique-coder-124** [zen-browser/desktop#1360]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When browsing i open several links in new tabs and often go through them one by one. When going through them if i decide to move one to a new workspace it will move the tab but any other tabs that have been opened just disappear. The tabs reappear if you create a new workspace in which case all the tabs that disappear suddenly reappear in the new workplace

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by abehidek** [comment]
Happens to me as well, adding a little bit (I think it's also related to this issue), when creating new tabs by using shift click (since I didn't entered them, they are considered "ghost tabs"), and them moving to a different workspace, these inactive/ghost tabs are also moved, however this only happens once, and when changing the workspace again these tabs stays at the previous workspace.

**Comment by abehidek** [comment]
New update seems to have fixed this issue for me, is it the same for you @unique-coder-124 ?
