### ISSUE TITLE
"New tab" button position 

### ISSUE THREAD

**Issue by XSentinelu** [zen-browser/desktop#1369]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After 1.0.0-a.35 release "new tab" button is in different position (in workspace section) and not bellow tabs as this was prior 35 release.

![1](https://github.com/user-attachments/assets/52de653e-0ed7-4a54-a98e-2ecbd56aeceb)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

>=1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is a design choice, please checkout [https://www.reddit.com/r/zen_browser/comments/1f8o7bp/tip_how_to_move_the_create_new_tab_button_at_the/](https://www.reddit.com/r/zen_browser/comments/1f8o7bp/tip_how_to_move_the_create_new_tab_button_at_the/)

**Comment by chriskirknielsen** [comment]
@mauro-balades To be fair, this is a drastic change in the UI, and it should be a option accessible to non-dev folks. Additionally, the solution provided in that link also removes the separator between pinned tabs and regular tabs, since it is part of the New Tab button.

Happy to hack away my own CSS file in the meantime, but I'd be grateful if you'd consider this as not completed (there are more pressing matters, so a low priority task would probably be fine!).
