### ISSUE TITLE
Incorrect icon in KDE app switcher

### ISSUE THREAD

**Issue by Inglan2** [zen-browser/desktop#1379]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In KDE, the windows switcher icon is wrong
![image](https://github.com/user-attachments/assets/4dc3c42d-811e-4870-a95c-5f1a48d8262f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Are you using app image, flatpak or portable?

**Comment by Inglan2** [comment]
> Are you using app image, flatpak or portable?

I think I installed from fedora repos or copr

**Comment by bl4xe** [comment]
> Are you using app image, flatpak or portable?

Having the same issue, installed through AUR

**Comment by definite-d** [comment]
Same issue, also installed from [AUR](https://aur.archlinux.org/packages/zen-browser-bin).
Zen Version 1.0.0-a.39

**Comment by mauro-balades** [comment]
Is the icon correct in any other display? Like the dock or desktop shortcut?

In other words:
Is it simply that there's no icon or is it just on the switcher?

**Comment by definite-d** [comment]
Just on the switcher.

This is how it looks in the Application Launcher:
![image](https://github.com/user-attachments/assets/43463dde-fa34-4641-a4bf-071272136d96)

And on the dock:
![image](https://github.com/user-attachments/assets/2420bea8-5f5d-4ea3-a5ea-a205ed0f4b8b)

But in the switcher (both this one and the Alt+Tab switcher, which I can't screenshot), it's the Wayland icon:
![image](https://github.com/user-attachments/assets/2d6b6816-257d-4e98-a2d3-718f6a053991)

**Comment by rojidev** [comment]
I found that you can work around this by creating a window rule in the KDE settings:
![image](https://github.com/user-attachments/assets/5641d741-8b75-4df6-9640-7c2e1d0a37a1)
You want to create a new rule and put `zen-alpha` in the `Window class (application)` field. Then `Add Property...` and find `Desktop file name`. Add that and enter the name of the desktop file, and make sure it's set to `Force`.
If you're using flatpak (like me) it'll be `io.github.zen_browser.zen`, otherwise it is probably gonna be `zen-browser` ^ ^

**Comment by definite-d** [comment]
@rojidev thanks for the workaround; it works for me as well. Though I found that I had to set the `Desktop file name` to `zen-browser`, like you suggested, and `Window class (application)` to `zen zen-alpha`.

**Comment by bioluks** [comment]
I was running into the same issue on Gentoo [GNOME] where zen-browser is distributed by custom overlays, and the fix was to have this exact line in the Desktop Entry (I don't use KDE and have to go the manual Desktop Entry editing way):
```
StartupWMClass=zen
```
Before my change it was `StartupWMClass=zen-alpha` and the wmclass didn't match because of that. This should fix the issue for both GNOME and KDE for anyone still looking for a solution.
