### ISSUE TITLE
Move 'New Tab' Button

### ISSUE THREAD

**Issue by nerdchills** [zen-browser/desktop#140]
### What feature would you like to see?

I'd like the option to have the 'open a new tab' button directly under my opened tabs instead of its current location.

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Because of the way the vertical tabs are implemented, this feature isn't possible and it's not very

**Comment by almighty-loaf** [comment]
Technical difficulties granted, I think this is a valid enhancement request and would like to elaborate as to why.

1. Tab interactions like rearranging, closing, pinning, muting, etc. happen almost exclusively in the top left. Pinned tabs even reduce their size to allow more to fit up there. Having everything happen in that quadrant except the very common action of opening a new tab seems arbitrary and also requires more mouse movement.
2. For those of us that expand the vertical tab bar to include tab titles, the size of the icon-only button makes it a comparatively difficult click target. Placing the New Tab button with label under the last tab would give it the same easy click target as other tabs.
<br>

I can understand the argument for having the New Tab button coexist with the sidebar toggle and workspace switcher buttons in the bottom left, since those two things are also conceptually "tab management" tools. But I'd argue that those are a somewhat different category of interaction separate from tab management of the immediate workspace, and don't ultimately benefit the user by being co-located.
<br>

### Workarounds
Within the _Customize Toolbar_ mode, you can move the New Tab button
1. above the first tab and all pinned tabs, where it will become an icon+text button and take on the width of the tab bar
2. next to the _Open settings_ button, where it will remain an icon-only button

Alternatively, middle-click the tab column, or just use Ctrl+T to open a new tab.
