### ISSUE TITLE
Multiple windows do not remember the last monitor they were on before the machine shut down 

### ISSUE THREAD

**Issue by andrrff** [zen-browser/desktop#1452]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

As soon as I turn off my system, I have multiple Zen windows open on different monitors. As soon as I turn on my machine, I always have to rearrange the windows that were previously open on the monitors.

This is happening in firefox too. (Firefox flatpak version: 129.0.2)

OS: Linux Fedora 40

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
@andrrff 

Because the positioning of windows isn't handled by the browser (Firefox or Zen), it is handled by whichever window manager / desktop environment that you're running. Where windows will be placed or not be placed when an application starts is largely managed by this...

So this is not really a bug with either browser, and thus not something that can be fixed by the Zen team.
