### ISSUE TITLE
CSS file not loading when opening an HTML file into the browser

### ISSUE THREAD

**Issue by GoodDea1** [zen-browser/desktop#1568]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Whenever I open an HTML file, index.html in my case, the HTML file was able to load in the browser, but not the CSS file so it's just text that's being displayed without any styling.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
I can't really do anything about it... Make sure you imported the CSS correctly, check the network tab if there has been an error and make sure the selectors correctly apply. Thanks!

**Comment by GoodDea1** [comment]
Alright, thanks for the help!

**Comment by Smorty10** [comment]
@mr-cheffy I am experiencing the same problem too, were I have two local files in the same directory:
- `index.html`
- `style.css`

and am properly embedding the css here:
```html
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
  <link rel="stylesheet" href="style.css">
</head>
```

But the css file does not load, compared to Firefox, where it *does load* correctly. So this issue is unfortunately not solved.

I'm also working with a gnu/linux system (Fedora 43)

**Comment by mr-cheffy** [comment]
It's probably an issue with your flatpak permissions, you might need to enable home perms but that means your profiles also need to be moved
