### ISSUE TITLE
Missing keyboard shortcuts for next and previous tab

### ISSUE THREAD

**Issue by SzybkiRabarbar** [zen-browser/desktop#1678]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In keyboard Shortcuts, the option to set a keyboard shortcut for next tab and previous tab has disappeared.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Windows

**Comment by cachesdev** [comment]
Please fix this! I can't understand how these settings were overlooked.

**Comment by plundration** [comment]
There are many shortcuts that have been thrown out it seems. I am missing the next/previous tab shortcuts too, I stuck zen on .3 I think, but had to upgrade because of the Firefox CVE. Please could you add these back?

What could be an interesting addition is a "previously accessed tab", so you could easily switch between two tabs?

**Comment by masfworld** [comment]
I'm not @SzybkiRabarbar but I think this issue is still relevant
