### ISSUE TITLE
Bookmarks place in new tab is sliding the tabs

### ISSUE THREAD

**Issue by konfitti** [zen-browser/desktop#1690]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It is like this:
![image](https://github.com/user-attachments/assets/e2f900ec-4c3d-462f-9e88-2f5edd116251)

And I think it should behave like this:
![zen](https://github.com/user-attachments/assets/c33ad621-f867-4110-8ebd-24b296c3c1b7)
made in Gimp™

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by Boaphlipsy** [comment]
This definitely seems like unintended behavior, since the Bookmarks do correctly get placed next to the tabs when not collapsed. 
Examples:

Uncollapsed
![image](https://github.com/user-attachments/assets/d046b183-c587-4013-a61d-72cc1344fdd5)

Collapsed
![image](https://github.com/user-attachments/assets/ac3e7f72-5dcc-40f1-9bd1-9d63543a14e1)

**Comment by Daniel-Mendes** [comment]
![image](https://github.com/user-attachments/assets/6052028d-1a50-447a-8e91-826f7102a6d6)


The left alignement is also strange
