### ISSUE TITLE
No longer able to set a toggle sidebar keybind

### ISSUE THREAD

**Issue by Samueru-sama** [zen-browser/desktop#1703]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Before the recent redesigning I was able to set a shortcut to the action Toggle Sidebar. 

Now this option doesn't exist anymore and the shortcut I had set prior isn't working either.  Now going to settings I can only see a "Toggle Sidebar's Width" option that doesn't do anything.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Linux

**Comment by mkuchak** [comment]
Yeah, I’m having bugs with the shortcut settings. With the new update, all my shortcuts were reset, which is really inconvenient, but totally acceptable given the work being done here! The problem is that now I can’t set the configurations anymore; the new shortcuts just aren’t being saved. And come on, advanced users need their shortcuts (I think that’s the biggest niche for Zen Browser, hehe). I hope this gets fixed as a priority. By the way, great job so far. Cheers!

**Comment by Samueru-sama** [comment]
The issue was fixed in the last update, now the action is called show the bookmarks sidebar and it works. Thanks a lot to the devs!
