### ISSUE TITLE
Temporary Containers Automatic Mode doesn't work on Zen Browser

### ISSUE THREAD

**Issue by Muko-Tabi** [zen-browser/desktop#172]
### What happened?

# Temporary Containers Extension Issue

## Extension Details
- Name: Temporary Containers
- URL: https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/

## Issue Description
The Temporary Containers extension is designed to automatically assign new tabs to temporary containers when the "Automatic Mode" setting is enabled. This feature works as expected in regular Firefox up to the current Developer Edition as of now, even if the extension is outdated. However, when using the Zen browser the "Automatic Mode" feature doesn't work.

## Steps to Reproduce
1. Install the Temporary Containers extension in Firefox.
2. Open the Temporary Containers extension settings.
3. Go to General and tick "Automatic Mode".
4. Open a new tab.

## Expected Result
When opening a new tab in step 4, the Temporary Containers extension should automatically assign the tab to a temporary container.

## Actual Result
When opening a new tab in step 4 in Zen Browser, the Temporary Containers extension does not automatically assign the tab to a temporary container.

##
- Would be nice if there's a workaround or the project can integrate the extension into it, since this is currently why I'm still using normal Firefox. Thanks in advance :D

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.12

### Severity impact

Medium, Enhancement

### What platform are you seeing the problem on?

Linux, Windows

**Comment by mauro-balades** [comment]
Does it still happen?

**Comment by Muko-Tabi** [comment]
yup still happen, same with Floorp and Librewolf as well

**Comment by howyay** [comment]
It still occurs on Zen, but works normal for me on Librewolf

**Comment by mauro-balades** [comment]
> yup still happen, same with Floorp and Librewolf as well

it's probably the extension's fault then, no?

**Comment by somerandom2** [comment]
> > yup still happen, same with Floorp and Librewolf as well
> 
> it's probably the extension's fault then, no?

@mauro-balades 
It is working on Librewolf 

https://github.com/user-attachments/assets/f8a89e74-10ef-4699-89d9-82abb6d4b324

**Comment by lbrooney** [comment]
I think I found a solution. Inspecting the Temporary Containers, you will immediately notice a lot of uncaught errors from `showOrHide` caused by L4943. The extension is trying to get a container with id `firefox-default`, but that does not exist.

Examining Temporary Containers source code, `showOrHide` is found in [`pageaction.ts`](https://github.com/stoically/temporary-containers/blob/main/src/background/pageaction.ts) with the line causing the throw at [L43](https://github.com/stoically/temporary-containers/blob/cbb39f7abbdf3c767bd1fbdc109394a0db169b05/src/background/pageaction.ts#L43). For *why* it's throwing, in Firefox you never reach the `else` instead the `if else` on [L31](https://github.com/stoically/temporary-containers/blob/cbb39f7abbdf3c767bd1fbdc109394a0db169b05/src/background/pageaction.ts#L31) is executed. In Zen that `if else` doesn't execute because the extension checks whether the default cookiestore id is being used by [`getting the browsers name`](https://github.com/stoically/temporary-containers/blob/cbb39f7abbdf3c767bd1fbdc109394a0db169b05/src/background/tmp.ts#L95) which gives `zen` and appending `-default`, but the default cookiestore id is [`firefox-default`](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/parent/ext-toolkit.js#38). The `else if` doesn't execute as `zen-default` does not equal `firefox-default` and instead the `else` executes which causes the error.

Setting `global.DEFAULT_STORE` in `/toolkit/components/extensions/parent/ext-toolkit.js` to `zen-default` makes Automatic Mode in Temporary Containers functional.

I can't comment whether this fix breaks other container extensions. If they hardcoded checking cookieStoreId against `firefox-default`, then this fix would break them.

**Comment by lbrooney** [comment]
This issue is still relevant.

**Comment by lbrooney** [comment]
You can manually fix Automatic Mode by following these steps:

1. Make sure to have Temporary Containters installed and that it's done its first install setup
1. Go to [about:debugging](about:debugging) 
1. In Debugging go to *This Zen*
1. Scroll until you see the *Temporary Containers* extension and click the **Inspect** button
1. A Developer Tools menu should pop out, click on **Storage** and within storage click the **Extension Storage** Tab and that should expand to display something with the name *moz-extension://<uuid>*, click it
1.  Some items should popup on the right, at the top should be **containerPrefix**, edit the item text from `zen` to `firefox`
1. Restart Zen and automatic mode of Temporary Containers should work.

**Comment by shankargopal** [comment]
Thanks for the suggestion @lbrooney but just to add that it didn't work for me.  In fact somehow it broke Zen itself; new tabs would just open to a blank page and I couldn't get to any of the settings pages.  Even more intriguingly, I deleted the Zen profile folder and then to get some other work done went back to normal Firefox - and that didn't work either!  I kept getting error messages like "Contextual identities disabled" when I tried my old shortcuts to open containers.  I eventually disabled and re-enabled the Temporary Containers extension in normal firefox, and that fixed it.  

I don't plan to go back to Zen just now as I don't have time to work on this and Zen without TC is not something I want to use.  But just thought I'd leave this here for anyone else who finds this bug.

**Comment by lbrooney** [comment]
@shankargopal Interesting. I wasn't able to recreate your issues when attempting on a freshly created profile, but I believe when I was first migrating over to Zen I had the same issue where Zen was completely broken, everything was just blank. IIRC mine was caused by copying my Firefox profile and just pasting it in the Zen profiles directory. I fixed it by:
1) creating a new profile in Zen (via about:profiles)
1) launch it to complete Zen first time setup, this generates profile folder contents and prefs
1) Close Zen and close Firefox
1) Then to move over the Firefox profile either:
   1) (I haven't actually tested this, but I think in theory it should work) copy over the contents of your Firefox profile to the Zen profile **EXCEPT** for `prefs.js`
      1) I think zen breaking has something to with some old value set by Firefox or more likely some value required by Zen that's not set by default
    1) (what I did) I wanted a relatively fresh profile so I manually copied over what I wanted carried over, based off information [here](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data#w_what-information-is-stored-in-my-profile)

Just to reiterate, I think the important part is not copying over the old prefs.js.

If you want to keep your old extension settings:
1) (if you didn't copy your whole profile over) copy `<profile>/storage/default` to the Zen profile (where extension data is kept, more specifically extension data is stored in the folders starting with `moz-extension+++`)
1) in your old Firefox `prefs.js` find the `extensions.webextensions.uuids` user_pref and overwrite the samenamed user_pref in the new Zen `prefs.js` or more ideally append it to the user_pref avoiding duplicates.

Unfortunately, my understanding is that Firefox settings set via about:preferences and about:config are saved to prefs.js so you'll have to reconfigure. I noticed no issues copying over my user.js, but I was using a fairly standard arkenfox setup so YMMV.

Then I fixed TC by during the previous steps I said above.

I could potentially help further diagnose the problem if you send me the exact error text or a screenshot of it, it almost sounds like the container tabs setting is disabled despite the fact that TC should force it on.

**Comment by shankargopal** [comment]
As said I stopped using Zen after this so don't have anything to share as
yet - am worried about risking my browsers again just now :-).  But I can
say that I didn't copy anything from the earlier profile at all - I just
downloaded the Zen AppImage on Linux and ran it, logged into Firefox Sync,
after some days of using it attempted your fix.  When it stopped working, I
then deleted the Zen profile folder.  But after that I returned to normal
Firefox as said and found the problems I reported.  I still am very
confused about how any of this managed to affect my existing Firefox
install. I should also note that subsequent to this experience, while
everything is working now, all the data from my earlier Firefox containers
such as their cookies etc. seems to have been deleted - when I return to
them now, I have to individually log in to each site again.
