### ISSUE TITLE
Workspaces Don't Crossover to New Windows

### ISSUE THREAD

**Issue by mtwb47** [zen-browser/desktop#1775]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

IDK if this is a bug, but it feels like one, so I will post here. When you have multiple workspaces, and then open a second window, the workspaces exist in the second window but any tabs that exist in the workspace are not there. They can only be accessed via the window that was opened first.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Not sure where to find this.
```

**Comment by sjclayton** [comment]
This isn't a bug... Workspaces don't ensure that open tabs stay persistent in the same workspace across multiple windows... new windows behave like they would in stock Firefox and other browsers. 😃

**Comment by mtwb47** [comment]
It may be how Firefox handles them but the "other browsers" thing is at least untrue when it comes to Vivaldi. But if this is the way it is, that's okay. It seems odd that you can then never use two workspaces at the same time, sort of dilutes the usefulness imho.

**Comment by sjclayton** [comment]
@mtwb47 

You can use two workspaces at the same time, in separate windows, just tabs aren't carried over from one window to another.

**Comment by MightyCoderX** [comment]
> @mtwb47
> 
> You can use two workspaces at the same time, in separate windows, just tabs aren't carried over from one window to another.

and why would that be a good thing?

**Comment by flifloo** [comment]
Related discussion: #924

**Comment by MadStoneDev** [comment]
I agree. That's the main reason most of us even use Workspaces, to keep certain tabs open but separate the uses. If I want my personal tabs, use the Personal workspace, or Work, etc. Those tabs should just reopen at selecting that saved Workspace.

**Comment by praxiq** [comment]
There seems to be some confusion about what behavior some users are expecting and why, so I'd like to weigh in. 

Zen presents Workspaces as a way to group tabs by project or theme. I can have two Workspaces with a different set of tabs open in each workspace, and I can easily switch between them. 

Now, what if I want to see both at once? I'd like to open a new window, and see one workspace in each. But there's no way to do that. 

As soon as you open a second window, it turns out that a workspace is not, in fact, a collection of related tabs... it's something more abstract and complex, because _each_ window now lets me switch between _each_ workspace, but with its _own_ set of tabs. There's actually a tab group _per workspace per open window,_ and no way to move these groups between windows. It's a bit tough to wrap your mind around the intended use case.

In contrast, Firefox now has "Tab Groups," and I can drag a group between windows, or right-click on one and select "Move group to new window." This is a useful feature, and there's nothing analogous to it in Zen.

I can see the rationale behind the Zen model - I have two monitors, and when I'm using two browser windows it's usually because I want to see two windows related to the _same_ project. I can select multiple tabs, or even "select all" within a workspace, and drag them to the corresponding workspace in another window. But it's very counterintuitive at first, and some documentation at least might be helpful. Something in the FAQ, perhaps?
