### ISSUE TITLE
Linux CLI installer not using download directory set by user-dirs.dirs

### ISSUE THREAD

**Issue by msantoma** [zen-browser/desktop#1799]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In the installation script is hardcoded to the `$HOME/Downloads` directory, but I don't have this directory as I have reassigned the `XDG_DOWNLOAD_DIR` to a different name in my `user-dirs.dirs`. It would be nice to have it check exactly what is the download directory that you are using. The problem in the script is in this line.

`zsync_file="${HOME}/Downloads/zen-browser.AppImage.zsync"`

My partial fix was to just replace it to the directory name that I'm using, but I wouldn't know how to do this generically.

(Also small typo in the output: dedecting -> detecting)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64 bits)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Enter your choice (0-3): 3
[i]
[w] Auto dedecting AVX2 support...
[i] Checking for updates...
[i] Checking for Update...
Warning: Failed to create the file
Warning: /home/user/Downloads/zen-browser.AppImage.zsync: Arquivo ou
Warning: diretório inexistente
                                                                                                                    0,4%curl: (23) Failure writing output to destination

[e] (⌣_⌣” ) Checking for Update failed, retrying...
```

**Comment by Samueru-sama** [comment]
>My partial fix was to just replace it to the directory name that I'm using, but I wouldn't know how to do this generically.

The script would have to define the variable:

```
XDG_DOWNLOAD_DIR="$(xdg-user-dir DOWNLOAD 2>/dev/null)"
```

And all instances of `$HOME/Downloads` have to be changed for `${XDG_DOWNLOAD_DIR:-$HOME/Downloads}`

Note that the script also doesn't follow the XDG Base dir specification, so all instances of `$HOME/.local/share` have to be replaced for `${XDG_DATA_HOME:-$HOME/.local/share}` for example. 

I'm really not a fan of the appimage install script because it is very inefficient and there is plenty of existing solutions out there that integrates and keeps appimages to up date like AM, Gearlever and the go-appimage daemon for example, by that I mean the script downloads the zsync file to compare versions to update, but that zsync file is meant for delta updates with AppImageUpdate instead. (that is it doesn't download the whole appimage when updating), it also extracts the whole appimage to get the .desktop and icon even thought the appimage runtime supports arguments to extract only those files, and it is also hardcoded to install at one location.

But anyway, if you want to venture making that PR fixing the issue you have that is more than welcomed I think.

**Comment by msantoma** [comment]
I have made the changes, but I can't find the repo where the `appimage.sh` is, so I don't know where to do the change.

**Comment by Samueru-sama** [comment]
> I have made the changes, but I can't find the repo where the `appimage.sh` is, so I don't know where to do the change.

I also could not find the `appimage.sh` when I first heard about it, it seems to be only hosted on the website, however I was able to [find the PR that added it](https://github.com/zen-browser/desktop/pull/1435).

I would just PR the file again to the top level of the repo.

**Comment by LeMoonStar** [comment]
> > I have made the changes, but I can't find the repo where the `appimage.sh` is, so I don't know where to do the change.
> 
> I also could not find the `appimage.sh` when I first heard about it, it seems to be only hosted on the website, however I was able to [find the PR that added it](https://github.com/zen-browser/desktop/pull/1435).
> 
> I would just PR the file again to the top level of the repo.

The script is located at https://github.com/zen-browser/updates-server/blob/18afa4eb5088f8d72aa00a17c9cadf0efbb6618e/appimage.sh
