### ISSUE TITLE
Find (ctrl-F) not functional in web panel

### ISSUE THREAD

**Issue by gnate-m** [zen-browser/desktop#1804]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

With a web panel open, ctrl-F searches the content of the page in the main window, not the panel.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hey so we're about a month since this post was added and after about 9 releases, the functionality has stayed the same. Since a lot of users use the web/side panel for multitasking, the search (ctrl-F) is more suited to affect the main web page.

I will be closing this issue post for now. Though, I do believe web/side panels will be getting a revamp at some point in the future. No definitive dates whatsoever, though.
