### ISSUE TITLE
Mouse forward/back buttons in web panel passes to main window

### ISSUE THREAD

**Issue by gnate-m** [zen-browser/desktop#1805]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

With cursor over active web panel (pinned or floating), forward/back mouse buttons don't mimic behavior of the forward/back arrows for the panel, rather it causes the page in the main window to move forward/back in history. Unexpected behavior re: window focus.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hey so we're about a month since this post was added and after about 9 releases, the functionality has stayed the same. Since a lot of users use the web/side panel for multitasking, the mouse forward/backward buttons are more suited to affect the main web page. 

I will be closing this issue post for now. Though, I do believe web/side panels will be getting a revamp at some point in the future. No definitive dates whatsoever, though.
