### ISSUE TITLE
Switching Workspaces Syncs Across Windows

### ISSUE THREAD

**Issue by apetl** [zen-browser/desktop#2005]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When switching workspaces on one window switches the workspace on all other windows. Did not happen on 1.0.1-a.7 happened on updating to 1.0.1-a.8

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by PushaG** [comment]
Yup, same here. Windows 11.

**Comment by atharva-p** [comment]
[from the latest release notes](https://zen-browser.app/release-notes)
> Added support for syncing workspaces

this is probably a feature? i havent' got to try out the new update yet. You should be able to turn it off in the settings if it's a feature

**Comment by sjclayton** [comment]
Happens for me as well on Linux... Agreed it seems like a bug, and if not, it should not be the default behaviour (should be user defined behaviour, ie. should have a pref to enable / disable it)

**Comment by shr1k** [comment]
Same here on MacOS as well. (1.0.1-a.8, MacOS Sonoma, 14.7)

**Comment by kevclark** [comment]
This was happening for me on 1.0.1-a.7 also (on 3 separate Linux instances), also confirmed still an issue on 1.0.1-a.8.

**Comment by mbaltrusitis** [comment]
#### expected behavior.

- Each Zen window should be able to display a different workspace (e.g., one window shows a 'work' workspace while another shows a 'personal' workspace).
- Workspaces should allow different extensions and Zen settings to be configured independently for each.

#### actual behavior.

- Currently, all Zen windows operate under a single workspace context. Switching the workspace in one window changes it for 
- All workspaces share the same extensions and settings, with no distinction between them.

#### supplemental info // context.

In previous versions of Zen, it was incredibly useful to have explicit partitions for the different contexts I use while browsing. For example, in my 'work' workspace, I don’t enable ad blockers or configure them with specific rules, as I work in ad tech. Meanwhile, in my 'personal' workspace, I prefer a stricter ad-blocking setup. Additionally, I need the ability to use these workspaces simultaneously—browsing news in my 'personal' workspace while debugging or coding in my 'work' workspace. These clear separations and independent configurations are essential to efficiently managing my workflows across different contexts.

**Comment by mr-cheffy** [comment]
I thought people wanted this, apparently not... Ill revert it back to how it was.. sorry!

**Comment by alike03** [comment]
I'm also not a fan, but would not revert it fully. I would add an option, where one can switch between the states.
Something like; Tab Management > Workspace > Sync Workspaces on all Windows

**Comment by mr-cheffy** [comment]
This has been fixed, thanks!

Ill prooobably release today

**Comment by lbngoc** [comment]
I think this feature should be available as an option under "Tab Management" setting.
I switched to Zen Browser from Arc and need the ability to synchronize the tabs across all windows instances, as I use the browser on multiple monitors

**Comment by mikedlr** [comment]
@lbngoc your comment isn't likely to get a response here on a closed ticket, but it sounds like a feature request which should probably go in [discussions](https://github.com/zen-browser/desktop/discussions). I think people already made similar requests so if you could find one and put it there you might get more response.
