### ISSUE TITLE
Pinned tabs gone after reopening the app

### ISSUE THREAD

**Issue by ocean-mars** [zen-browser/desktop#2011]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Pinned tabs are gone every time I close the browser & reopen it

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

macOS - Intel

**Comment by kristijanribaric** [comment]
Is it just the pinned tabs?
Can you confirm that you have in settings under `General --> Startup --> Open previous windows and tabs` turned on?
Also, under `Privacy & Security --> Browser Privacy --> History`, what option do you have selected in the dropdown?

**Comment by aadilayub** [comment]
I was experiencing this issue as well. It turned out "Clear history when Zen browser" was turned on. It was toggled automatically after an update.

IMO it's a big issue that users can't expect their settings to remain the same between updates, let alone such important ones that result in data loss and workflow interruptions.

EDIT: In fact, I know remember when this happened. A few weeks ago there was an update after which all my data, my entire browser profile got wiped out and I had to set up Zen from scratch. I was too busy to report that issue when it happened. The "clear history after close" was toggled by default in the new profile. A very bad default IMO.

**Comment by mr-cheffy** [comment]
Ill move this into https://github.com/zen-browser/desktop/issues/1062, to organize better
