### ISSUE TITLE
Can't have two rows of icons at the bottom of vertical tabbar

### ISSUE THREAD

**Issue by Simply-Jeff** [zen-browser/desktop#2092]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I expected that i can add buttons and stack em up in two rows at the bottom of vertical tabbar, for example, if i add 7-8 buttons then, there will be two rows of buttons 

![Screenshot 2024-10-14 1058412](https://github.com/user-attachments/assets/3a20a4f9-f6d8-4f3d-ab58-4d07a9e24f7e)

But buttons get just added one after another and the horizontal width of the tabbar increases, rather than the buttons getting piled in two rows 

![Screenshot 2024-10-14 1103302](https://github.com/user-attachments/assets/0915c9d6-8278-405d-854c-e8053d3a9585)

and also when i add new tab button in the toolbar, then it doesn't displays it's text "New Tab"

![Screenshot 2024-10-14 1058413](https://github.com/user-attachments/assets/9e2d9096-e094-49f0-a26c-8516fd07ab2b)
![Screenshot 2024-10-14 1103303](https://github.com/user-attachments/assets/53727a67-cb41-4f48-a9f3-1df23684e295)

 and one more thing, when i split view two tabs, then there's no highlight on the border of the active split tab (btw, i don't have the zen mod for removing the highlight installed)

And one feature request, please make it so that i can easily split view tabs, with functionality similar to that of arc browser, and the split view as a button to be added in the toolbar

Also, I can't move buttons like extension to the tabbar

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
hey looks like you got three different things in one post. itd be great if you split them up cuz they're all affecting slightly different things. 

> I expected that i can add buttons and stack em up in two rows at the bottom of vertical tabbar, for example, if i add 7-8 buttons then, there will be two rows of buttons

I've asked the dev and they said this wasn't actually a bug and was intentional. Of course that doesn't mean it can't be a suggestion so I would move this to the discussions tab for further considering.

> and also when i add new tab button in the toolbar, then it doesn't displays it's text "New Tab"

It shows the text in the sidebar but not in the toolbar because we want to avoid cluttering up the toolbar with text. Most browsers don't have any text (except the url bar) in the top bar to keep things clean. Not sure what else I can say for this one. 

> and one more thing, when i split view two tabs, then there's no highlight on the border of the active split tab (btw, i don't have the zen mod for removing the highlight installed)

could you check if you still get this issue in the latest ver? (1.0.1-a.14)

> And one feature request, please make it so that i can easily split view tabs, with functionality similar to that of arc browser, and the split view as a button to be added in the toolbar

please send this over to the discussions since that's where suggestions and feature requests go.

> Also, I can't move buttons like extension to the tabbar

a couple of the buttons and elements in the toolbar (triple dot menu, extensions, and urlbar) can't be dragged. we'd have to wait for javascript-functional mods to alter them (which is in the works, I hear).

**Comment by salamijason** [comment]
No response in 5 days, will be closing this issue. Please reopen if you are still facing this issue.
