### ISSUE TITLE
Keyboard shortcuts tab is empty in Settings

### ISSUE THREAD

**Issue by CrynTox** [zen-browser/desktop#2111]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The Keyboard shortcut tab doesn't allow me to customize my shortcuts.
![image](https://github.com/user-attachments/assets/b19e4662-25fe-4c28-8a2f-b53e7f8048e8)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
Cannot reproduce this here in 1.0.1-a.9 on Linux.

**Comment by greeeen-dev** [comment]
Can reproduce on macOS aarch64 when resetting keyboard shortcuts back to default. This is happening because this completely deletes the shortcuts JSON from your profile folder, and Zen does not regenerate this file (or read from a default set of keyboard shortcuts), resulting in this error.
<img width="488" alt="Screenshot 2024-10-15 at 10 47 12" src="https://github.com/user-attachments/assets/003a266d-961a-4e4d-866c-deb4282e5816">

Copying the zen-keyboard-shortcuts.json file from a fresh profile to my existing profile solved the issue.

**Comment by mr-cheffy** [comment]
This has been fixed for version .10, thanks a lot!
