### ISSUE TITLE
Shortcuts doesn't work

### ISSUE THREAD

**Issue by quivXe** [zen-browser/desktop#2189]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When i have keyboard language set to polish and im pressing eg. ctrl alt e, I get ę. It doesnt trigger default shortcuts. I mean I have set this shortcut to ę, like every other shortcuts and it works for now, but i think its not intended, especially when i click leftAlt + e, i also get ę which also will trigger shortcut even tho it should be only with ctrl + alt + e.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 i think, looking on download date as i downloaded zip from yours main page on 16.10

### What platform are you seeing the problem on?

Windows

**Comment by andreaswilli** [comment]
I experience the same issues with the Swiss keyboard layout on macOS.

**Comment by mr-cheffy** [comment]
Just so that I can understand it, is it just a display issue?

**Comment by andreaswilli** [comment]
I think there is more than one issue. Here are my observations after some more experimentation:

Initially (or after resetting to default) the shortcuts show up as expected and for me at least they work (for the most part, see below [*]). But when I try to set a shortcut manually e.g. `Option+Cmd+c` for compact mode it shows up like this and does not work anymore:

<img width="720" alt="image" src="https://github.com/user-attachments/assets/78767e3e-ce9a-4ac5-927a-803dbb406aba">

I suspect that the issue with this shortcut is the collision with the Firefox shortcut as it opens the element picker in devtools instead.

The json file shows the following changes after setting the shortcut:

```diff
 {
   "id": "zen-compact-mode-toggle",
-  "key": "c",
+  "key": "ç",
   "keycode": "",
   "group": "zen-compact-mode",
   "l10nId": "zen-compact-mode-shortcut-toggle",
   "modifiers": {
     "control": false,
     "alt": true,
     "shift": false,
-    "meta": false,
+    "meta": true,
-    "accel": true
+    "accel": false
   },
   "action": "code:gZenCompactModeManager.toggle()",
   "disabled": false,
   "reserved": false,
   "internal": false
},
```

When I try to set it to `Option+Cmd+x` it also shows up incorrectly as `Option+Cmd+≈` but pressing the combination does trigger the assigned action.

Yet another behavior occurs with the shortcut `Option+Cmd+u` which triggers "view source" with default settings, but starts working after setting it manually (displaying as `Option+Cmd+¨`) similar to what is described in the issue description.

[*] While most default shortcuts work initially, I can reliably break the compact mode shortcut by changing any of the other shortcuts. Is there already an issue for this? If not I can create one.

Edit: Everything described above was tested on Zen `1.0.1-a.10 (Firefox 130.0) (aarch64)`.

**Comment by mr-cheffy** [comment]
Ill push this to twilight and then release today to stable. Thanks a lot!

**Comment by andreaswilli** [comment]
Thanks for the quick patch. The display issues described above are solved 🎉 

These issues remain in Twilight `1.0.1-t.11 (Firefox 131.0.3) (2024-10-19) (aarch64)`:

- In the default settings the `Option+Cmd+u` shortcut for `Close Split View` does indeed collide with `View Page Source (Safari)`. Now it even warns me about the conflict when trying to set the shortcut manually.
- The Toggle Compact Mode shortcut `Option+Cmd+c` collides with the element picker shortcut (not in the list, so no warning) and stops working (triggers element picker) after modifying the default config in any way.
- And something new I noticed: The Swiss layout is QWERTZ instead of QWERTY (meaning the Z and Y keys are swapped). The shortcut editor detects the wrong inputs e.g. when I press `Option+Cmd+z` it shows up as `Option+Cmd+y`. Outside of the editor the inputs are detected correctly, so I need to press  `Option+Cmd+y` to trigger the assigned action.
