### ISSUE TITLE
When changing keyboard shortcut with non-US keyboard layout it display wrong information in settings

### ISSUE THREAD

**Issue by MannixMD** [zen-browser/desktop#2198]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When you try to change a keyboard shortcut in settings while having other then US/English keyboard layout the settings displays actual letter instead of a shortcut combination
![Screenshot 2024-10-18 at 11-20-33](https://github.com/user-attachments/assets/7b7a2183-5d12-4678-bcbc-9e050fc5b33b)
Instead of `ć` it should say `Alt+Ctrl+C`

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
I'll take a look at this tonight if no one else gets to it first

**Comment by rve0** [comment]
Hey, bumped into this article today:
https://tkainrad.dev/posts/why-keyboard-shortcuts-dont-work-on-non-us-keyboard-layouts-and-how-to-fix-it/

This find reminded me I started looking into this particular issue a while back. There's some findings I posted at this ticket: https://github.com/zen-browser/desktop/issues/1028, That ticket is also added to this public backlog, so I'll look for it after finishing this comment so it can be marked as duplicate to this one.

Based on my (limited to Windows, US & US intl) testing was; it seems that the code-property rather than key-property is more stable. keycode currently doing fine as well, but since it's deprecated it might be worthwhile to check out the code-property instead. This one also has the added benefit of being able to differentiate between left and right modifiers, which means more shortcut options (and more shortcuts = more better). 

But the entirety is a bit messy and enough to warrant a proposal to the IEFT.

**Comment by RayZ3R0** [comment]
@rve0 Does this issue still persist in the latest version?

**Comment by rve0** [comment]
> @rve0 Does this issue still persist in the latest version?

![image](https://github.com/user-attachments/assets/d762eac1-57dd-4927-a257-faec958a3d02)
 
Unfortunately it's the same behavior on 1.0.1-a.14 as previous versions.

**Comment by rve0** [comment]
a.16 idem, but it likely hasn't been worked on for these two increments

**Comment by Lin-Den-Dev** [comment]
Too bad, I will have to remap shortcuts somehow. Same issue for the newest version US-Qwerty keyboard with Win POL keymap
