### ISSUE TITLE
Pin Tab is lost after close pin tab with right click

### ISSUE THREAD

**Issue by wasawin** [zen-browser/desktop#2235]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Pinned tabs will disappear after closing the pinned tab by right-clicking to close the tab. When restoring the tab, the tab is still pinned, it needs to be unpinned and re-pinned.
![Screenshot 2024-10-20 064743](https://github.com/user-attachments/assets/45b045d5-48ec-43a5-ad24-aa39a405d560)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
no output
```

**Comment by salamijason** [comment]
Hey! I'm not quite clear on what you mean. If possible, could you send a screen recording of the issue?

**Comment by tylertylerday** [comment]
I think they mean that when you close a pinned tab from the context menu, that it shouldn't also "un-pin" the tab. The tab should stay pinned, reset the url to what you pinned it to, and just focus the next tab instead.

**Comment by salamijason** [comment]
> tab should stay pinned, reset the url to what you pinned it to, and just focus the next tab instead

@tylertylerday hmm alrighty if that's what they meant:

@wasawin 
In the tab management section of the setting page, you'll see an option to change what Ctrl+w (ctrl+w would usually close non-pinned tabs) would do to a pinned tab. The "Close Tab" button in the context menu still completely removes the tab from the list as that is intentional.
![image](https://github.com/user-attachments/assets/ff5829ff-0686-41e1-a8b6-ba3a8fba0c24)

But I suspect you meant something else:

> restoring the tab, the tab is still pinned, it needs to be unpinned and re-pinned.

so please do give us more info on what you mean here.

**Comment by wasawin** [comment]
Sorry for not recording the clip and I have updated the version.
It seems that some of the fixes have been made.

Fixed the issue:
- Pinned tabs are not pinned to the tab.

Bug:
- Pinned tabs disappear if you close the tab by right-clicking, but CTRL+SHIFT+T can bring them back.
- When closing the tab, sometimes the saved pin will be cleared.
- Reopening the browser may cause the saved pinned tab to be cleared


https://github.com/user-attachments/assets/9dd89cb2-4cd4-4e4b-a28d-068a1d60b517

**Comment by salamijason** [comment]
> Pinned tabs disappear if you close the tab by right-clicking, but CTRL+SHIFT+T can bring them back.

This is intentional behavior.

That was definitely a bug at 0:39. <---- here is the actual bug, i believe. @mauro-balades (i dont have perms to rename post sry abt that)
At 1:20, the reset pinned tab doesn't work because you didn't "Replace Pinned URL with Current" after the bug cleared it. 

> Reopening the browser may cause the saved pinned tab to be cleared

often times, this happens because  "Replace Pinned URL with Current" was not done first.
