### ISSUE TITLE
Cycling through tabs with Surfingkeys navigates to different workspaces

### ISSUE THREAD

**Issue by ll931217** [zen-browser/desktop#2292]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

[Surfingkeys config](https://gist.github.com/ll931217/14ee9bef2775d27d9357cdcefcc93c1d)

Main config regarding issue:
```javascript
// Next/Prev Page
map('K', 'E');
map('J', 'R');
```

This keymap is just using `gt/gT` in vim, where you move between the left/right tabs respectively. Here is a diagram of what is happening:

![image](https://github.com/user-attachments/assets/dd56d3a8-861e-4125-b658-51a1c46e22b9)

The numbers are the order in which I opened the tabs, so if I am on "Workspace 2", I want to navigate from tab "3" to tab "5", it will go to tab "4", unless I cycle to the next tab it won't go to tab "5".

I don't know if this is possible to make it so that tab order is unique for each workspace

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
This happens because of how workspaces are currently implemented in Zen, basically all workspaces are is hidden tabs, so when you're in say Workspace 1 the tabs open in the other workspaces are still there, they're just not shown.... so the ordering is the same as how they're opened.

Workspace 1
Tab 1
Tab 2
Tab 3

Workspace 2
Tab 1
Tab 2
...

Workspace 3
Tab 1
...

So when you try navigating to the next tab (below) from the last tab in Workspace 1 you will end up switching to Tab 1 of Workspace 2, not to Tab 1 of Workspace 1, or just not switching tabs at all, and remaining on that tab.

This is very annoying behaviour for sure, and I hope it is something that gets addressed in the future, but as of right now this is the way things are.

Hope that helps!! 😀

**Comment by Richard-Woessner** [comment]
Seems to be a feature for Firefox specifically

**Comment by sjclayton** [comment]
@Richard-Woessner 

This has nothing to do with Firefox, as workspaces are not implemented in Firefox... This is purely to do with the way workspaces are implemented in Zen currently, and some functionality of certain extensions, namely Vimium, not being allowed to work in the way they are intended because of it.

**Comment by juampivallejo** [comment]
I could be completely off, but it looks like the extension is using this to get the previous / next tab:
https://github.com/brookhong/Surfingkeys/blob/f152a9a831ed4c357f072a531400d62c226be974/src/content_scripts/common/normal.js#L942

I think Zen could fix this by replying to that call with something similar to what is used by the native shortcut (Ctrl + Tab), which currently works without switching workspaces.

**Comment by Quicksilver151** [comment]
why wont fix? some of the surfingkeys functionality is really broken by zen. including moving tabs between windows and also navigating forward and backwards on the list of tabs
