### ISSUE TITLE
remove workspace gradient

### ISSUE THREAD

**Issue by plutonium-239** [zen-browser/desktop#2372]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I cannot seem to be able to reset the new workspace gradient to an "unset" state i.e., the default browser theme shows. Neither is there any documentation/help about this feature.

I was just testing this feature out and I want to go back to using my browser's theme (which is provided by the SuperGradient mod).

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
Agreed, there should be an easier way to toggle / disable this... should not be necessary to use about:config to set `zen.theme.gradient` to false.

Some people out there may want to still just use SuperGradient, just because Zen implements similar functionality that should not mean that mods designed for said functionality are made obsolete.

**Comment by plutonium-239** [comment]
It seems like it is no longer a problem; removing all the colors from a workspace (right-clicking them in the color picker) successfully removed the workspace gradient for me.

Closing.
