### ISSUE TITLE
Zen completely breaks to unusable state after closing the last regular tab while having pinned tab(s) opened (exact steps to always reproduce + video included)

### ISSUE THREAD

**Issue by stripedgoat** [zen-browser/desktop#2474]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1.Visit a pinned tab on a workspace.
2.Close the regular tab that is open underneath the pinned tabs. This will cause the browser to get it's own will and decide on it's own to open the very last pinned tab which wasn't even previously loaded / visited.
3.Now close that last pinned tab that Zen opened for you.
4.A normal new tab is finally opened for you. Close it.
5.Zen breaks. You can no longer visit any website until you restart the browser.

See the video below:

https://github.com/user-attachments/assets/e79433f8-5122-44ef-84a1-a032d68fc6b3

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.16

### What platform are you seeing the problem on?

macOS - Intel

**Comment by pufferfish-connoisseur** [comment]
I get a similar issue on macOS - apple silicon, using tab unloading instead of pinned tabs. Steps to reproduce.

1. Have 2 tabs opened, ex. google is tab 1 and bing is tab 2. 
2. Have tab 2 currently focused.
3. Unload tab 1 (the top one), issue occurs both when done manually and automatically
4. Close tab 2, have tested both with cmd+w and vimium's close tab keybind (x)

Boom, broken!

**Comment by mr-cheffy** [comment]
This has been fixed for version 17 (currently building). Terribly sorry, guys...
