### ISSUE TITLE
Dragging a pinned tab unpins the tab

### ISSUE THREAD

**Issue by l4kr** [zen-browser/desktop#2508]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

As per title, I think the drag operation itself should simply open the current pinned tab URL in a new tab. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have implemented a solution to allow dragging a pinned tab to open its URL in a new tab. This change modifies the tab dragging behavior in the browser to create a new tab with the pinned tab's URL when dragged. Here are the key changes:

1. In `tabbrowser.js`, I updated the `_numVisiblePinTabs` getter to count only visible pinned tabs.
2. In `tabs.js`, I modified the `_handleTabDrag` method to create a new tab with the pinned tab's URL when dragged.
3. I adjusted various references to `_numPinnedTabs` to use `_numVisiblePinTabs` for better accuracy.
4. I removed the absolute positioning of pinned tabs in `tabs.css` to allow for smoother dragging.

I also created pull request: https://github.com/zen-browser/desktop/pull/2515


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by salamijason** [comment]
are you still getting this on a22? (latest as of this comment)

**Comment by salamijason** [comment]
Could you provide a screen recording? I'm not quite getting what you mean by:

>  I think the drag operation itself should simply open the current pinned tab URL in a new tab.

**Comment by salamijason** [comment]
No response in 5 days, will be closing this issue. Please reopen if you still get the bug.
