### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by ValgulNecron** [zen-browser/desktop#2615]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Tab navigation seem to not be working.
when on a website let say youtube, and we press the tab key the element selection should move on the next one but do not in zen. it do work fine on latest firefox.

The same issue apply to arrow navigation when using the left or right arrow to move nothing happen. also work fine on latest firefox.

Also just found out that ctrl + tab do not change the browser active tab

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 (Firefox 132.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Nightwish2710** [comment]
I can attest to this. I have Zen on Mac and Windows. Built-in keyboard's and external keyboard's arrow keys work perfectly, but on Windows, external keyboard's arrow keys won't work.

**Comment by jrjaro18** [comment]
lemme explain it in little more detail:

lets say i have 2 tabs open, i.e., loaded, reddit (a pinned tab) and google (a normal tab), now when i press ctrl + tab from reddit instead of going to the google (the next loaded app) it goes to the right next app even if its unloaded and starts loading it, so it will go to the twitch (next pinned tab) and then the zen (next pinned tab), and then i can reach the google tab, this i believe is due to the cyclic nature of how they are handling this, ignoring whether the tab is loaded or not, should be a simple fix, ig, and again when i press ctrl + tab from google, it wont go to the reddit but to the youtube (an unloaded essential app) 

![Screenshot 2024-11-11 010235](https://github.com/user-attachments/assets/67132c0a-d35a-4fdf-b3f8-0673729b26e6)

**Comment by ValgulNecron** [comment]
that not the issue i encounter and this is a design choice if it should go to next tab in order or next loaded tab.

the issue i encounter is that ctrl tab and other shortcut (given above) simply don't work on my windows machine.

also to continue with what [Nightwish2710](https://github.com/Nightwish2710) said about macos, my linux machine have no issue.

edit: he deleted his message.

**Comment by codeleux** [comment]
Version: Mozilla Zen 1.0.1-a.19 (from AUR)
OS: Arch Linux (6.11.9-zen1-1-zen)

Having the same issue with zen, built-in tab and arrow keys won't work in any situation, however numpad's arrow keys (KP-Right, KP-Left, etc.) do work.

Only solution I could think for now is downgrading the browser, will update if it works.

Edit: My main pc has the same browser version (1.0.1-a.19) and works totally fine, I'm not sure what's going on.

Edit 2: Uhm, so I just reinstalled zen and rebooted my laptop, it works now, I'm quite confused tbh, weird bug.

**Comment by MemQu** [comment]
This can't be intentional, because I'm randomly having it work and not after restarting zen.

Tab and shit+tab

This is in conjunction with

#2743

**Comment by mr-cheffy** [comment]
Ill move it to https://github.com/zen-browser/desktop/issues/2743
