### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by asuh** [zen-browser/desktop#273]
### What happened?

It'd be great to get this browser on Homebrew so that we could do something like `brew install zen-browser`.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64, macOS - Intel

**Comment by AlternateRT** [comment]
Unless Zen becomes a signed/notarized app, it is unlikely to be accepted into the main Homebrew/homebrew-cask repo due to a recent [policy change](https://brew.sh/2024/05/14/homebrew-4.3.0/#:~:text=Homebrew/homebrew%2Dcask%20requires%20code%20signing%20of%20all%20casks.%20Expect%20removal%20of%20casks%20that%20are%20not%20code%20signed%20from%20Homebrew/homebrew%2Dcask%20in%20future.%20This%20is%20because%20code%20signing%20is%20required%20on%20Apple%20Silicon%20which%20is%20used%20by%20a%20growing%20majority%20of%20all%20Homebrew%20users.):

> [Homebrew/homebrew-cask requires code signing of all casks](https://github.com/Homebrew/brew/pull/17002). Expect removal of casks that are not code signed from Homebrew/homebrew-cask in future. This is because code signing is required on Apple Silicon which is used by [a growing majority of all Homebrew users](https://formulae.brew.sh/analytics/homebrew-os-arch-ci/365d/).

---

I have no idea if @mauro-balades intends to ever notarize Zen, so for now the only viable option for adding Homebrew support is to maintain a [Homebrew Tap repo](https://docs.brew.sh/Taps).

**Comment by mauro-balades** [comment]
I do not plan on adding this, however, anyone is welcome to try do this 👍🏽

**Comment by KennethHoff** [comment]
Literally every single app I've ever installed on my Mac, except like 1 (and Brew itself) was installed via Brew. I highly recommend doing this if you want to support the Mac ecosystem.

**Comment by AlternateRT** [comment]
For the record, maintaining a Homebrew Tap repo for Zen would be very easy. All you really need to do is host a `zen-browser.rb` file with the following structure:
```
homebrew-tap-name <-- the name of the repo on github
├── Casks
│   └── zen-browser.rb
└── README.md
```

Then, all macOS users would have to do to install Zen is run:
```
brew tap zen-browser/tap-name
brew install --cask --no-quarantine zen-browser
```

Or alternatively just:
```
brew install --cask --no-quarantine zen-browser/tap-name/zen-browser
```

That would be far more straightforward than what is currently being instructed on #53.

----
P.S. I see that someone attempted to submit Zen into the main homebrew-cask repo (https://github.com/Homebrew/homebrew-cask/pull/183028). The submission from there could be used as an outline for `zen-browser.rb`.

**Comment by mietzen** [comment]
I think it would be best if the tap would be create as a repo inside zen-browser organization. @mauro-balades would you be open to create that repo? I think we find enough people here who are willing to open a PR with the home brew cask script. I also think that having a one liner like @AlternateRT suggested:

```
brew install --cask --no-quarantine zen-browser/tap-name/zen-browser
```

as install instruction would be far better.

**Comment by MillerApps** [comment]
Absolutely think it's essential to have official Homebrew support rather than a third party. Not only that, but it's nearly expected for any open-source projects with Mac support to be available in Homebrew.

**Comment by SundayPowerEndre** [comment]
It is quite essential, this is the first software i have wanted to test for a long time that was not on Homebrew. I especially think that if you want to get privacy concerned mac users, many of them prefer/require to install and manage packages via terminal. 

As @mietzen mentions above, i think you'll find enough people that would be willing to do the work, if you were open to the contribution. I really hope you will reconsider @mauro-balades.

**Comment by OmerWow** [comment]
With all appreciation an respect to the project, the only reason I've yet to install it is because it's not available via Homebrew.
Getting it done would be great, pretty much required for many Mac users

**Comment by martin-braun** [comment]
@mauro-balades Homebrew is a de-facto standard for MacOS. I highly recommend doing it. I agree with @adrian-goe. If you want to see this browsers success on the Mac world, a first-class deployment over Homebrew is necessary, because Apple's way to doing things is either selling your soul or being a caveman.

**Comment by tomatau** [comment]
Please add to brew, this is a blocker for trying it Zen browser

**Comment by SundayPowerEndre** [comment]
https://github.com/zen-browser/desktop/issues/1038
