### ISSUE TITLE
Pinned tabs disappear when using multiple browser windows

### ISSUE THREAD

**Issue by xperr** [zen-browser/desktop#2763]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When dragging a tab to create a new browser window and then closing both windows the pinned tabs will disappear in both workspaces.

https://github.com/user-attachments/assets/c1462945-c44d-4765-8589-8526a31fa677

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by LeMoonStar** [comment]
Hey! This will be fixed in the next release,a s pinned tabs have been completely reworked (and split into "essentials" and "pinned tabs")!
You can already take a look at the [release notes](https://zen-browser.app/release-notes#1.0.1-a.18) if you want.

I will keep this issue open until the changes have been released. If you want to try them you can also already check out the current Zen Twilight build!

**Comment by xperr** [comment]
Thats great! Thanks! :-)

**Comment by LeMoonStar** [comment]
`1.0.1-a.18` is now released and this should be fixed!
Thank you
