### ISSUE TITLE
The linux version isn't updated?

### ISSUE THREAD

**Issue by Kimbix** [zen-browser/desktop#2781]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The version 1.0.1-a.18 isn't available for Linux, when executing the Appimage through the terminal, it says it is that version, but when running the app and going into the settings, it shows the previous version.
![image](https://github.com/user-attachments/assets/f87bb1a0-6eaa-4a71-91d0-284a57e87998)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Linux

**Comment by axeleroy** [comment]
I'll add additional context since it did not help that bot: [on Flathub](https://flathub.org/apps/io.github.zen_browser.zen) the latest version is `1.0.1-a.19`, which is two versions behind [latest](https://github.com/zen-browser/desktop/releases).

So to reiterate: is the Flatpak version even updated anymore? I don't remember a release mentioning Flatpak being deprecated.

**Comment by axeleroy** [comment]
[The release notes for 1.0.1-a.22](https://www.zen-browser.app/release-notes/1.0.1-a.22) may explain why:

> This build rolls back to version 1.0.1-a.19 due to the number of bugs and complains. Sorry!
