### ISSUE TITLE
Pinned tabs and essentials appear in private mode

### ISSUE THREAD

**Issue by damian-ds7** [zen-browser/desktop#2816]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

after a.18 update when I open private mode pinned tabs from all workspaces and essential tabs are visible. Also something that's maybe related to #2789 is that normally after unloading pinned and essential tabs don't have favicons loaded but in private mode they do.

![image](https://github.com/user-attachments/assets/446f3ead-3b5b-4f62-a69c-bd8cf05c7a6d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Linux

**Comment by damian-ds7** [comment]
Is there a way to change this behavior temporarily in browser?

**Comment by sannidhyaroy** [comment]
I'm also experiencing this after the recent update. Private browsing is unusable, cuz all the pinned tabs from every workspace opens up in private browsing, causing the system to lag. The tab bar ui also appears broken, potentially because it tries to accommodate every pinned tab.
Fortunately, there's a workaround, as I noticed, if I close the pinned tabs using the `✕` button of the tabs. That doesn't close the pinned tabs in the normal workspaces, but they don't appear in the Private Window, which should be the expected behavior in the first place.

EDIT: Don't remove the pinned tabs in Private Browsing Window. You don't wanna learn it the hard way 🙂

**Comment by oupadhyay** [comment]
I don't recommend deleting the pinned tabs in private as I believe it will delete your pinned tabs in the normal workspaces later. Don't ask me how I know (I am sad).

**Comment by sannidhyaroy** [comment]
> I don't recommend deleting the pinned tabs in private as I believe it will delete your pinned tabs in the normal workspaces later. Don't ask me how I know (I am sad).

Learnt it the hard way. Since, I tested it with one tab and it didn't seem to remove it on the normal window, I went ahead and removed all of them. And I was pretty happy for some time as everything was going well, until in the normal window I needed to pin a tab, and I see only that tab pinned and other pinned tabs removed. 🙂

**Comment by MrPiggy105** [comment]
You should also ignore essentials and pinned tabs with popup windows (like for signing into Google accounts).

**Comment by shishkin** [comment]
If bots suggest halucinated workarounds to bug reports just for fun I wonder if bots are also who write these buggy features in Zen in the first place 🤔

**Comment by kristijanribaric** [comment]
Fixed for next release.
