### ISSUE TITLE
No Themeing Option When Workspaces is Disabled

### ISSUE THREAD

**Issue by ido1901** [zen-browser/desktop#2894]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When workspaces are disabled, the theming (gradient) option isn't available when right clicking the sidebar. Enabling workspaces shows the option, but I do not want to use those.

![image](https://github.com/user-attachments/assets/5a165749-1a54-4bac-ad8e-b386cf684440)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a19

### What platform are you seeing the problem on?

Windows

**Comment by Mgldvd** [comment]
The same thing happened to me when I disabled workspaces, and I can't reactivate it because I prefer using the "Panorama Tab Groups" extension, which doesn't work well with workspaces. In fact, I much prefer their approach of allowing you to see all the tab groups. It could actually be a great addition to workspaces.

https://addons.mozilla.org/es/firefox/addon/panorama-tab-groups/

**Comment by mr-cheffy** [comment]
This is expected as gradients are attached to Workspaces. Each workspace table has a theme field, meaning they have to have a workspace linked to them unfortunately. This is why we managed to have gradients for different workplace... Sorry
