### ISSUE TITLE
"Pop up tabs" seem to open random tabs when they are no longer needed.

### ISSUE THREAD

**Issue by RabbyDevs** [zen-browser/desktop#3055]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/8be2783d-2f4d-4a62-ab77-1b8859d874e7

^ Refer to this video, do note that I do have the Helldivers Companion app open as a pinned tab. I do not know if this is reproducible.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.19 (64-bit) (optimized)

### What platform are you seeing the problem on?

Windows

**Comment by neonfuz** [comment]
I am having the same issue. It seems to happen with those sites that open pop-up windows without visible tabs, back button, etc. Normally (IE in firefox) when you close these windows, they just disappear. But in Zen, it seems that these windows start showing other tabs when you try to close them.

This is a massive issue, right now I have a ton of tabs inaccessible because they're stuck in this type of window which doesn't have visible tabs.

When this gets fixed, I would appreciate a way to restore these tabs, or a method to convert those windows to normal windows.

Thanks

Edit: It appears that most of the tabs that get moved are pinned tabs? it's probably to do with the new implementation of pinned tabs interacting with popup windows

**Comment by limonkufu** [comment]
I also started seeing this. It would probably be fine if I could actually close these tabs easily even manually

**Comment by mr-cheffy** [comment]
This has been fixed in version 20, thanks!
