### ISSUE TITLE
Problem with star-history in README.md

### ISSUE THREAD

**Issue by Victor-Baert** [zen-browser/desktop#3107]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I see this in the readme but you seem to be talking about comparing to other browsers, shouldn't we be seeing Chrome and Brave on here like the links in the source suggest?
![image](https://github.com/user-attachments/assets/be880542-d5d2-49cd-9dc4-f551751d68f1)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

NA

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
NA
```

**Comment by DallinYauney** [comment]
yeah I was wondering about that too...

[this page](https://star-history.com/blog/how-to-use-github-star-history) from their website seems to suggest that, for embedding these graphs in the readme, we should be using an iframe, rather than a `<picture> <source>` style embedding, though I'm not sure what the best practices are on what access token to use to set this sort of thing up.

**Comment by mr-cheffy** [comment]
![Image](https://github.com/user-attachments/assets/5a344eaa-45e5-4a1a-b038-04b5e57c651f)

It's very weird, idk why its not including other browsers...

**Comment by mr-cheffy** [comment]
Should be fixed now
