### ISSUE TITLE
Sync suggests getting the Zen mobile app

### ISSUE THREAD

**Issue by MiniGod** [zen-browser/desktop#3137]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After logging in and enabling Sync, I was told to "Open Zen Browser on your mobile device".

As far as I know, Zen does not exist on mobile.

![image](https://github.com/user-attachments/assets/76139dbd-ec26-48bd-b831-045a8defad9a)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by dannymagnus** [comment]
I have had the same issue

**Comment by max-niederman** [comment]
@dosu this was closed incorrectly.

**Comment by Dreamingwolf** [comment]
> [@dosu](https://github.com/dosu) this was closed incorrectly.

This issue was not closed incorrectly. The Devs have no interest/intention of creating a mobile version so any issue dealing with references to a mobile version are meaningless to them. They obviously copied/pasted some code and can't be bothered to clean it up. So they just closed the issue rather than dealing with it.
