### ISSUE TITLE
Sidebar width is removed

### ISSUE THREAD

**Issue by ShakeSphereStuff** [zen-browser/desktop#3236]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When switching from a.19 to a.20, the option to toggle the sidebar's width was not viewable in the settings
Version a.19
![Screen Shot 2024-11-27 at 18 40 35](https://github.com/user-attachments/assets/77b53a41-14fb-4266-b047-83aaf4681229)
Version a.20
![Screen Shot 2024-11-27 at 18 40 40](https://github.com/user-attachments/assets/a45c28c3-336e-4cdb-b2a1-465563d15080)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.20

### What platform are you seeing the problem on?

macOS - Intel

**Comment by realSilasYang** [comment]
Release notes for 1.0.1-a.20 indicate that Zen has removed collapsible sidebar. This change is quite disappointing for me, as I frequently rely on this feature to toggle and achieve a wider view of the webpage.

**Comment by n7itro** [comment]
> Release notes for 1.0.1-a.20 indicate that Zen has removed collapsible sidebar. This change is quite disappointing for me, as I frequently rely on this feature to toggle and achieve a wider view of the webpage.

It will be added back as a mod

**Comment by mort666** [comment]
> Release notes for 1.0.1-a.20 indicate that Zen has removed collapsible sidebar. This change is quite disappointing for me, as I frequently rely on this feature to toggle and achieve a wider view of the webpage.
> 


That is unfortunate...  Well I reverted back to the previous 'working' version and won't be updating it...

**Comment by zplawecki** [comment]
same for me, rolled back to .19 and won't be updating soon since .20 is broken for me

**Comment by hiwer** [comment]
> same for me, rolled back to .19 and won't be updating soon since .20 is broken for me

me too..

**Comment by Deadcows** [comment]
yep, very disappointing regression in functionality. Used the hotkey a lot

**Comment by gautierlabarre** [comment]
Same it's the feature I prefer on zen :(

**Comment by Video-Nomad** [comment]
Yeah, this is quite unfortunate indeed. This was very useful feature and having the full width sidebar all the time is annoying as hell. Toggling it on and off constantly is not the best workflow either. This should be the core functionality as it was before...
P.S. downgraded to a19... quite unfortunate.

**Comment by hiwer** [comment]
I feel like this last update was not good at all. There are a lot of errors that none of us probably expected.

**Comment by zplawecki** [comment]
It's wasn't even possible to turn it on, even temporarly, at least for me - and additionally this "full width" sidebar broke the way bookmarks were displayed

**Comment by gautierlabarre** [comment]
I am a bit scared that the mod will work for a few time and then as it's just a mod it'll be unmaintained at some point and the feature will be broken

**Comment by Video-Nomad** [comment]
> I am a bit scared that the mod will work for a few time and then as it's just a mod it'll be unmaintained at some point and the feature will be broken

Mod will never have the level of support or seamless functionality as a core feature would. It's not surprising users are concerned.

**Comment by itsTyrion** [comment]
I always had it set to auto expand on hover, it's one of THE features for me - nothing else, except MS Edge, has vertical tabs like that

**Comment by ShakeSphereStuff** [comment]
> I always had it set to auto expand on hover, it's one of THE features for me - nothing else, except MS Edge, has vertical tabs like that
- You... you know [Arc](arc.net) exists right

**Comment by realSilasYang** [comment]
So sad guys that 1.0.2-b.0 officially removed collapsible sidebar expand on hover.

**Comment by FallenChromium** [comment]
This was a very weird decision that definitely broke my workflow. While I acknowledge that the previous state of the tab bar has probably been a UX tradeoff (hover isn't easy to pull off sometimes, especially when compact mode is enabled) and it might've been a nightmare to support, but a combination of a shortcut toggle to make it full-width or compact no matter the mode you use (show on hover a.k.a. compact mode or show always) was the thing I've enjoyed the most in this browser.

Releasing this change without releasing the extension to bring the old behavior back is a mistake. Making a shortcut for a pop-up list with quick search by tab name (esentially a "%"-prefixed search in the address bar filtered by current workspace) would've compensated for some of the frustration. Any other alternative way to navigate through the tab names while having the tab bar collapsed 99% of the time would've helped, to be honest.

Thanks for the Zen, I'm a huge fan of your vision. As a "sorta product manager" person I guarantee you will face a lot of backlash every time you delete a feature that was there, because there WILL be a noticeable amount of people affected. I hope you'll get it sorted in a way to not just get the "old way" back to the users but in a way to make the whole tab navigation process much better in general. 

You can ping me for some ideas or MVPs in the meantime - I am very unhappy with the current version, and since the browser is my main tool I'd be very happy to help you to resolve it faster.

**Comment by zplawecki** [comment]
for god's sake, guys, stop messing around with the collapsible sidebar, I'm fed up with constantly reinstalling browser to older versions because You keep breaking things...

**Comment by gautierlabarre** [comment]
I'm using the beta release and it still works as expected for me.

**Comment by mort666** [comment]
> for god's sake, guys, stop messing around with the collapsible sidebar, I'm fed up with constantly reinstalling browser to older versions because You keep breaking things...

Which version are you running that still has the old tab/sidebar?? Given how much normal functionality keeps getting stripped out things, I've stuck to 1.0.1-a.22 on most machines but the annoying update notification keeps banging on, I don't know how tho because all the update services for Zen are Blacklisted on my network DNS, would love to know how it keeps getting the IP for the download servers, I've a suspicion it is using DoT or similar (again that has also been disabled, Mozilla stuff has a annoy habit of bypassing it).

**Comment by zplawecki** [comment]
> > for god's sake, guys, stop messing around with the collapsible sidebar, I'm fed up with constantly reinstalling browser to older versions because You keep breaking things...
> 
> Which version are you running that still has the old tab/sidebar?? Given how much normal functionality keeps getting stripped out things, I've stuck to 1.0.1-a.22 on most machines but the annoying update notification keeps banging on, I don't know how tho because all the update services for Zen are Blacklisted on my network DNS, would love to know how it keeps getting the IP for the download servers, I've a suspicion it is using DoT or similar (again that has also been disabled, Mozilla stuff has a annoy habit of bypassing it).

I'm using 1.0.1-a.19, it was the last stable version, all other are bugged as hell... but now after downgrading it doesn't even ask if it can be updated, just does it after next PC restart, so I have to constantly reinstall it

**Comment by mort666** [comment]
> I'm using 1.0.1-a.19, it was the last stable version, all other are bugged as hell... but now after downgrading it doesn't even ask if it can be updated, just does it after next PC restart, so I have to constantly reinstall it

So a.22 has been fine for me, the only problem I've been having is Bluetooth audio on Linux related and that has plagued most versions I've used even those before a.22 and a.19. So there is a directory called 'updates' usually in the location you installed Zen where updates are staged before installing. If you delete the directory and what I've done is set the access perms on it so only 'root' or 'Administrator' depending on the machine being Unix based or Windows that way Zen can't write to it during normal running. 

I've not noticed any errors/crashes because it can't update. The other thing I've done temporarily is to block DNS lookups for the updates servers, which sometimes helps. I say sometimes, because sometimes it will resolve the addresses, and I'm like 70% sure it is because the DoH URL in about:networking keeps randomly being set to a 'mozilla' cloudflare DoH endpoint and even tho DoH is disabled it will use it for some lookups for internal stuff...

**Comment by zplawecki** [comment]
thanks, I'll try the solution with removing the directory and setting Administrator access untill they fix the most annoying things... 

for me the worst behaviour is that when I'm in Compact Mode and have address bar hidden, it keeps appearing anytime I move cursor around the top of window, but it detects cursor faster than it was before, so address bar keeps covering any top menu I have on a specific web page, it's not usable this way :/ 

and I'm using Windows btw. ;)

**Comment by mort666** [comment]
Yeah there are two things I can't abide round corners and url bars and other random crap that decide is is a good idea to cover up a large chunk of the viewing area... I also noticed there are a lot of ppl reporting issues with text entry tasks with input vanishing, problems with selecting, etc, etc... so this URL bar and tabs situation is fast becoming a problem and as someone who almost constantly is manipulating stuff in the URL bar. That is a deal breaker...

I'm probably going to see how things go till after the new year and it everything is still heading in this trajectory I'll be switching browsers again for the like 15th time in 12 months.... to be fair, I've been using this one both Windows and Linux, I hadn't put it on my macOS machines yet and this may have killed that plan too..

**Comment by n7itro** [comment]
@mort666 Firefox recently reworked how the URL bar works. Zen Browser is always updated to the latest stable version of Firefox for security, which is why there were a lot of bugs in a.20-22.

@zplawecki Zen Browser is now in beta, and the developers have stability as the top priority. I recommend upgrading to the latest version (`1.0.2-b.2`)

**Comment by zplawecki** [comment]
> @zplawecki Zen Browser is now in beta, and the developers have stability as the top priority. I recommend upgrading to the latest version (`1.0.2-b.2`)

I did, fortunately it seems to have most of blocking issues fixed and I'm aware it's "just" beta, but suprises like adress bar covering top of page aren't pleasant when You use such browser as a "daily" ;)
