### ISSUE TITLE
Massive performance tank

### ISSUE THREAD

**Issue by keplerHaloxx** [zen-browser/desktop#3246]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since I've updated to version 1.0.1-a.20 I've noticed that Zen loads webpages way slower than before. YouTube can take up to 15 seconds to load while Google Chrome takes ~3 seconds.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Version a20 is filled with some critical bugs due to upgrading firefox version to 133. a21 is going to be released soon, please try that when it comes out. Closing this for now, do reopen if this still happens in a21. For now, I would suggest downgrading to a19 until a21 comes out, which should be very soon.
