### ISSUE TITLE
Release `1.0.1-a.22` running Firefox 132

### ISSUE THREAD

**Issue by lizclipse** [zen-browser/desktop#3274]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Both upgrading to `1.0.1-a.22` and installing it directly result in an install that is based on Firefox 132, not 133 as both mentioned in the README and as in `1.0.1-a.21`.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

v1.0.1-a.22

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by different55** [comment]
a22 is a revert to 132 as most of the issues in a20 and a21 were apparently caused by the upgrade to 133. That's also why they didn't get caught in the nightlies, because Twilight was still based on 132.

[Source](https://www.reddit.com/r/zen_browser/comments/1h1su8q/ok_this_is_what_ill_do/)

If you take a look at the commit, a22 is just a version bump of a19 so the autoupdater picks up on it.
https://github.com/zen-browser/desktop/commit/d1ecbc3f6125b2e832aa042d2a8c775678e7deb7

**Comment by lizclipse** [comment]
I did try to look at the commit diffs, but it's not super obvious to me. I assume that the upgrade to 133 will happen soon though (if so, is there any tracking for it)? Otherwise it may be worth updating the README in the meantime to try and reduce confusion.

**Comment by different55** [comment]
I haven't run across any tracking on GitHub or comments from the dev about it, but yeah, like you I'd guess it'll happen soon. This issue might be the only place tracking it.

About the README, it *was* correct for the https://github.com/zen-browser/desktop/tree/1.0.1-a.22 a22 release, but it seems like the README's updated to 133 as the transition attempts to happen again. This repo has the dev branch set to default instead of the stable branch... not really sure what those terms mean for a project that's currently only releasing alphas. It is confusing though to have your default front page not reflect the current state of what people are downloading.
