### ISSUE TITLE
Will there be native .deb for zen browser in future

### ISSUE THREAD

**Issue by Midnight0507** [zen-browser/desktop#328]
### What feature would you like to see?

i have issues with flatpaks and for people who wanna try it nativey will there be a native package in future

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
There is no plan for official .deb pkg.
U cold try appimage pkg if the issues persistent in flatpak.

**Comment by sandenbergmelo** [comment]
It would be really nice to have native versions of the browser.

**Comment by ivanjx** [comment]
i think providing .deb and/or .rpm versions are important for firefox web browsers due to the fact that flatpak has no support for sandboxing and you need to set up security manually with appimage and tar installs. correct me if im wrong.

https://support.mozilla.org/en-US/kb/install-firefox-linux?as=u&utm_source=inproduct#w_security-features-warning

edit: alternatively, snaps can also ship with apparmor profiles but it seems that providing snap package would trigger some kind of people here.

**Comment by jj10133** [comment]
flatpak is super slow, for browser avoid tbh just my opinion we need native build
