### ISSUE TITLE
Styling breaks when trying to customize toolbars in Compact mode 

### ISSUE THREAD

**Issue by Mimieam** [zen-browser/desktop#3492]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Styling breaks when trying to customize toolbars in Compact mode 

<img width="521" alt="image" src="https://github.com/user-attachments/assets/2fb775d6-756d-45b6-a7e9-28ab074bda28">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-t.0 (Firefox 133.0) (2024-12-10)

### What platform are you seeing the problem on?

macOS - Intel

**Comment by multimokia** [comment]
This is still an issue with latest (1.0.2-b.1), confirming on Windows 10.

It'd be really appreciated if the team could avoid moving things around without prompting for it. I set things up explicitly, and/or leave them like so for a reason and would greatly prefer if changes were made, the toolbar would not be touched in updates, especially if I cannot undo them due to these issues.

**Comment by sezamn1** [comment]
i agree it's annoying, and still not fixed :(
using Arch Linux btw

**Comment by mr-cheffy** [comment]
Should be fixed now 👍🏽
