### ISSUE TITLE
Please add an option to disable the floating URL bar

### ISSUE THREAD

**Issue by SubtleMuffin** [zen-browser/desktop#3539]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Please add an option to disable the floating URL bar. It is *VERY* annoying.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by 22ispencer** [comment]
this seems to be intended behavior as seen here, quite a bummer, especially with the ui bugs it has right now

https://github.com/zen-browser/desktop/issues/3516#issuecomment-2532907965

**Comment by vegidio** [comment]
Came here to say the same; the new search bar has a terrible UX.

Don't use Apple/Google's approach of deciding for the users what they want. Please create options to let us enable/disable features that we don't like.

**Comment by y2k04** [comment]
My browser updated and I have got to say that it is super unintuitive for me. Don't fix what ain't broke!

Anyway, please add a toggle 🙏

**Comment by karamanliev** [comment]
+1
it looks bad, it feels bad and it's annoying.

**Comment by fredriks-eltele** [comment]
My biggest gripe with it is that clicking on the address input puts a cursor exactly where you clicked, instead of selecting the whole URL..

A decade of muscle memory has me typing into the middle of the existing URL 100% of the time.

**Comment by romibi** [comment]
I don't like the floating URL bar either …
~~I'm just glad that pressing F6 (which i use quite often) still behaves as it always has 😄~~
*Edit: Nope, not once you start typing …*

**Comment by zakiur** [comment]
I don't hate the idea of having more options but I think the floating URL bar has been implemented wrong. It is a beta build so I think the devs have more coming in the future. In my opinion the URL bar should have an option to toggle it on or of and the options to span the full width of the URL bar or not. Also it should have a floating feel to it and not be so much offset from the URL box above it. Also agree with @fredriks-eltele about the position of the cursor when selecting the URL and not selecting the address when first clicked has thrown me off a bit.

I appreciate the work put in so far. I think if a feature exists it should not be taken away without any reason and a new feature put in to replace the already working feature. It should always be added in with the existing feature and defaults should be exercised with caution. 

Thank you for a great browser.

**Comment by romibi** [comment]
> It is a beta build

Wait, I did not intentionally sign up for beta builds …
… how can I go back to stable?

Edit: Just realized: maybe there are no stable 😄

**Comment by GalletaFresca** [comment]
Yes, please. The old version was faster to use and this one makes more difficult to double click the URL since it moves from the fixed bar to the float panel after the first mouse click.

**Comment by alaza5** [comment]
Either add a toggle or implement it properly

Currently, when opening a new tab:
1. It focuses on the "normal" URL bar
2. When typing, you can see the text appearing in the "normal" URL bar
3. Then the floating URL bar pops up, forcing me to shift my focus and search for the text I just typed

It's driving me insane

**Comment by helixhammer** [comment]
Another vote here. Was upset to see that it forced, I can't stand it unfortunately. I see a Zenmod to turn it on but not off :(

**Comment by CraftingDragon007** [comment]
I really don't understand why they would force you to use this. It's really buggy and annoying

**Comment by ColetteDiskette** [comment]
For me, if I use compact mode hiding the address bar, when this spawns it's *way* off center and to the right, and since I can't disable it, I can't even work around the issue in the meantime without just entirely disabling compact mode (which at least centers it, but I still don't understand how this isn't redundant since the address bar is still ... you know, right there.)

Please give us toggles when adding things like this. It doesn't take much to push me away from a fork and go back to vanilla Firefox, and this coupled with being bombarded by a new welcome screen with no warning when the browser went from alpha to beta along with my UI getting mangled, causing me to check the breaking changes bit of the changelog and seeing none pertaining to my UI issues (way more than what's been mentioned here) is not giving me confidence that future changes will be user-respecting.

I love Zen browser and would like to regain that confidence.

**Comment by german-enriquez** [comment]
It should be easy to revert that hideous floating address bar. It's super counter intuitive.

**Comment by vegidio** [comment]
Less than 24 hours after the latest release this issue has become the most 👍'ed issue in the history of this repo. So, it's safe to assume this change was a lapse in judgment from the maintainers since many users clearly disliked this feature:

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/c289d002-db6b-4e51-8a1f-014f1ac478f9" />

I hope an update to let the users disable this feature comes soon.

**Comment by Kodehawa** [comment]
Yeah this is awful. This is driving me insane. All my muscle memory is gone, and now opening new websites feels like a legitimate chore. Why break what works like this? It's legitimately easier to use something else than to try to use the new address bar.

**Comment by LightJack05** [comment]
Yep, can only agree. It might look fancy, but it just hurts to use... 😅
If this doesn't get fixed soon, I'll probably also go back to vanilla Firefox... Don't like the look as much, but they have been making progress.

**Comment by stuartmaxwell** [comment]
Is this actually a feature?? I came here to log a bug and was surprised to learn this was intentional. This is honestly unusable and will need to switch back to Firefox if this won't be fixed. I appreciate that Zen is pushing some boundaries and trying new things, but this has gone too far now.

**Comment by yoonthegoon** [comment]
Looks like we're getting our fix soon.

https://zen-browser.app/release-notes/#1.0.2-b.1

![image](https://github.com/user-attachments/assets/bc0898d5-75f0-47a0-8555-b49dd5c3486d)

**Comment by Kodehawa** [comment]
still kinda confused as to why it's "legacy" though. the new bar is unironically unusable tbh

**Comment by yoonthegoon** [comment]
Maybe not lol

I can't seem to find anything new in settings and even adding 
```js
// ~/Library/Application Support/zen/Profiles/<PROFILE>/prefs.js

user_pref('zen.view.use-deprecated-urlbar', true);
```
doesn't appear to make any changes

**Comment by ColetteDiskette** [comment]
> Added a preference to disable the new floating URL bar (May be open to bugs, the preference is used as a deprecated feature)

Having a normal address bar is a "deprecated feature"?

Yeah, I'm going back to Firefox. It's obvious this browser's vision isn't what I thought it was.

**Comment by mhov** [comment]
Deprecating the NORMAL url bar will be a deal breaker.  This floating one deserves to be a Mod at best.

**Comment by kalvinpearce** [comment]
Looks like you can enable the old url bar by going to `about:config`, searching for `zen.view.use-deprecated-urlbar` and setting it to true.
![image](https://github.com/user-attachments/assets/0fdc3449-d321-47f3-8af0-467a8d464ec8)

I can confirm this is working for me on `1.0.2-b.1` MacOS build

**Comment by yoonthegoon** [comment]
I was just coming back to mention that adding that preference I mentioned earlier did _kinda_ do the fix. Issue is it's clear, making it unusable, so I'ma have to mod more settings.

<img width="558" alt="image" src="https://github.com/user-attachments/assets/d2176da0-c53f-4ef4-bc7a-9e94286d6e41" />

**Comment by kalvinpearce** [comment]
> I was just coming back to mention that adding that preference I mentioned earlier did _kinda_ do the fix. Issue is it's clear, making it unusable, so I'ma have to mod more settings.
> <img alt="image" width="558" src="https://private-user-images.githubusercontent.com/71526721/394997809-d2176da0-c53f-4ef4-bc7a-9e94286d6e41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzQ3OTIsIm5iZiI6MTczMzk3NDQ5MiwicGF0aCI6Ii83MTUyNjcyMS8zOTQ5OTc4MDktZDIxNzZkYTAtYzUzZi00ZWY0LWJjN2EtOWU5NDI4NmQ2ZTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAzMzQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYTdhYzk5Zjc5MDUzZWJiYmVmNzRhY2QzNzFmYTJiZDc3YjY0M2VkYThmOTc0NTYxMDJmMWFjZDUwZmMxNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nez_V87BXIEFlD8gn2J_u70Nyt5oEe_YQ0nt31ojvjQ">

Sorry to jump the gun, just realised I am having the same issue with transparency too 😞

**Comment by yoonthegoon** [comment]
Here's the change that makes this impossible to look at

https://github.com/zen-browser/desktop/blame/52a607d0fb016dadc73099de71e8682438508d7c/src/browser/base/content/zen-styles/zen-urlbar.css#L25

```diff
  #urlbar-background {
-   background: var(--zen-dialog-background);
+   background: var(--zen-toolbar-element-bg) !important;
+   outline: none !important;
  }

This was made going into 1.0.2-b.0 but not reverted for 1.0.2-b.1

**Comment by vesk4000** [comment]
There is [this fix](https://github.com/zen-browser/desktop/issues/3516#issuecomment-2532938566) that I found in one of the issues, which seems to work for me. (Note that you need to disable the `zen.view.use-deprecated-urlbar` option in `about:config`, since this fixes both the floating and the transparency issues -- basically it reverts it pretty close to what it was before the update).

![2024-12-12 10_50_15-Zen Browser](https://github.com/user-attachments/assets/8859918c-84b5-44a7-b545-a2fe7843b51a)

This whole thing is quite frustrating to be honest. **Now, don't get me wrong, I'm grateful for all of the work that the developers have put in for free to make this cool browser.** However, updates like these kind of hearken back to using Firefox for me, where just as you've made your browser setup all nice and how you want it, they would make updates that brake it and just seem illogical. Of course, with browsers it's very important that you update, because of security updates, so it's not like I can just stop updating my browser.

The floating URL bar might make sense, if you have your URL bar in the sidebar. But I really prefer my URL bar at the top, and I like that they kept the option of having it there. However, if you have your URL bar at the top, the floating URL bar just makes no sense at all -- as in, it's not just a preference thing, it breaks all kinds of UI sensibilities. The URL bar (especially the long one that we have on top) is a text box, so when you click on it, you expect to be able to edit the text in it, but instead what happens is that this floating URL bar appears, that is actually smaller than your URL bar on top, which is just not intuitive. And there's no way that you can tell me that this looks better:


![2024-12-12 10_57_46-New Tab — Zen Browser](https://github.com/user-attachments/assets/d856c4e7-ce9f-4311-aa20-e5d203991f2b)

**Comment by yoonthegoon** [comment]
I've got the longer more annoying solution for effectively the same results lol

Mine requires you enable `zen.view.use-deprecated-urlbar`

https://github.com/zen-browser/desktop/issues/3613#issuecomment-2539060116

**Comment by nneto** [comment]
In compact mode I really like the floating bar when I Cmd/Ctrl+K or Cmd/Ctrl+L to go to a new URL or search for something. I really hope they keep the option to the user preference. Even thought the floating bar gained a lot of hate, I would be sad if it was just removed altogether instead of being a option.

**Comment by vegidio** [comment]
> In compact mode I really like the floating bar when I Cmd/Ctrl+K or Cmd/Ctrl+L to go to a new URL or search for something. I really hope they keep the option to the user preference. Even thought the floating bar gained a lot of hate, I would be sad if it was just removed altogether instead of being a option.

Even though I'm one of those that hated the new floating bar, I also don't want it removed because I'm sure there are people out there that liked it.

My biggest complaint is how the new floating bar was shoved in our face without giving us an option to disable if we don't like it. Which is especially bad in this case because it has a lot of bugs.

I rarely advocate to have a feature removed. I prefer to give the users the option to choose, so each person can use the product the way they like, not what the devs tell us to like.

**Comment by SubtleMuffin** [comment]
I feel that the authors are very reluctant to revert their changes regarding the floating URL bar. In the new version (1.0.2-b.1), setting `zen.view.use-deprecated-urlbar` to true disables the floating bar, but it causes text to become illegible due to transparency settings.

> There may be bugs, as this preference is used as a deprecated feature.

So as written in the new release note.

Frankly, I am tired of tinkering with the browser just to restore it to its original working state. I have now decided to go back to Firefox. Thank you for the three-month journey, Zen Browser.

**Comment by yoonthegoon** [comment]
Unfortunately, I think I'll follow suit.
The main thing I appreciated it for was its sidebar tabs without needing any obnoxious header taking up space (and although tree style tabs are useful, I preferred the simplicity of simple vertical tabs without need for any configuration).
But with the number of issues I've lately been facing like having a blank space above my topmost tab (because I had to disable workspaces because I couldn't close the last tab with <kbd>Cmd</kbd> <kbd>W</kbd>), it would just be simpler for me to use Firefox Nightly for now.

Understandably there will be issues with Zen Browser for now as it just finally made it into beta, so I'd like to at least check up on the direction things have gone once it's out of beta.

**Comment by romibi** [comment]
@SubtleMuffin why close the issue though?
I don't see a hidden setting as this issue beeing solved …

**Comment by SubtleMuffin** [comment]
> @SubtleMuffin why close the issue though? I don't see a hidden setting as this issue beeing solved …

If you type `about:config`, look for `zen.view.use-deprecated-urlbar`, and set it to `true`, the address bar is back.

**Comment by romibi** [comment]
I know that but I don't see that as solving this issue …
A normal urlbar should be an option in the normal "Look and Feel" settings, otherwise this issue is not solved in my opinion …
How it is now … having this as a "hidden deprecated feature" I expect will result in more and more bugs in future …

**Comment by vegidio** [comment]
My friends, as others have already said, it's clear that the developer doesn't want to have this fixed. And it's fine, it's his project, but I also followed the same path the others have posted here and I came back to Firefox because a working URL bar is more important to me than side tabs.

Actually, if side tabs are the only thing that made you try Zen, you can download Firefox Nightly builds, that has this feature already. For those that stay, good luck.

**Comment by romibi** [comment]
Hm looks like we might be lucky:
c67fc71

_**Edit/Update:**_
https://zen-browser.app/release-notes/#1.0.2-b.2
> Added the very requested, very needed, feature rich, blazingly fast, innovative URL bar option we had in previous versions

Yay 🥳 
That changelog entry made me giggle 😄
