### ISSUE TITLE
URL bar with too much items block click

### ISSUE THREAD

**Issue by marcelovbcfilho** [zen-browser/desktop#3661]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The new URL bar is awesome, love that it is on the sidebar, but on some sites, like youtube,there are too much extra icons appearing on it which is blocking me to click on the url bar to change the url.
Here is an example screenshot, I think that some of this icons are unnecessary and could be hidden, but this is just my POV.
Not sure if its possible but, add some settings to hide extra url bar icons? My opinion here, but the lock(https site) is unnecessary, the enhanced tracking protection also could be removed and made a new setting in the settings screen, the picture in picture is also unnecessary, there already a huge label on the video stating that we can use picture and picture and also the new translate is unnecessary, I disabled the translation so it should be hidden and also the zoom, icon, maybe hide it on hover?. But again, my opinion here, don't even know if it's possible. Could be like a hover to hide? I don't know TBH.

In this image I'm hovering the URL bar, the screenshot doesn't show, but my mouse is literally on top of it. Without hovering it looks clean.
<img width="363" alt="Screenshot 2024-12-12 at 12 49 27" src="https://github.com/user-attachments/assets/e26a2768-4053-42d5-9ef2-e957ad10ba81" />

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

macOS - Intel

**Comment by Laflamme** [comment]
I agree that this is a problem: the Firefox URL bar was never designed to be this narrow. 

Instead of hiding anything, I recommend making the URL bar two rows high, with the actual URL on top and all its controls below. That would preserve all current and future functionalities of the URL bar while making it more consistent with the vertical design of the toolbar.

**Comment by neurokitti** [comment]
yeah try using this:
https://zen-browser.app/mods/a5f6a231-e3c8-4ce8-8a8e-3e93efd6adec/

or just swap the sidebar mode to have the url at the top

**Comment by itsleemcguire** [comment]
This issue is really bacd on the latest version and the mod neurokitti suggested doesnt work, its the icons in the bar at the top of the tab list that you can barely click on when theres more than two icons, I can basically only click on the very far left few pixels of the bar on some sites. I dont need to know about permissions or site information, PLEASE add an option to remove these useless icons!
