### ISSUE TITLE
Floating URL bar first result has broken padding on top

### ISSUE THREAD

**Issue by Numline1** [zen-browser/desktop#3666]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The first result in the search/URL bar is not correctly centered and has a bigger padding on the bottom than on the top

![image](https://github.com/user-attachments/assets/ecf9b3ce-e7e2-4497-9e3d-7b9b56b86fcf)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Smooth-E** [comment]
Can somewhat confirm. This is probably due to a separator between the main entry text and its description being included even if there is no description.

![Two top suggested entries of the floating toolbar. Second entry has a description.](https://github.com/user-attachments/assets/2676241d-2292-45af-89f2-e6c79adb7226)

I am running Zen `1.0.2-b.1` on Windows 11.

**Comment by Smooth-E** [comment]
The suggestions list was updated in `1.0.2-b.2`. Check out if the issue still persists. I think it is gone now.

![URL bar searching for "some search query"](https://github.com/user-attachments/assets/04f4c0fa-3f6f-40d0-9b9e-066f2d71a9dd)

**Comment by Numline1** [comment]
I can confirm this is fixed in b.2. Thank you @Smooth-E
