### ISSUE TITLE
Floating and transparent url bar still sucks

### ISSUE THREAD

**Issue by Muhammad-Mohid-Khan** [zen-browser/desktop#3700]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

You can go change it in about:config (DEPRECATED) but it still does not eliminate the transparent issue 

    when you click the URL it is not being selected, you need ctrl+a
    the theme is inconsistent with anything
    the position left/right is not centered at times
    the original URL bar at the top remains as an empty black hole?
    it adds nothing to the functionality
    there was already zen mod for this which did it better
    
    this is such a useless feature just revert it back already man its terrible no one asked for this we already have a mod for this if someone wanted theres no point of adding it and adding no option to toggle it completely 
    
    ( this was a reply in a issue similiar to this but im making a new one so its highlighted more since the issue is answered with changing the about:config which does close to nothing ) 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Latest

### What platform are you seeing the problem on?

Windows

**Comment by chenasraf** [comment]
Please revert this feature, put it behind a setting or config, and do more usability/UX testing before pushing such a major change. The idea is fine but the implementation is very flawed and not thoroughly thought out and tested.

**Comment by prypyet** [comment]
The amount of times ive tried to select the url to copy it and have failed to do so because the option doesnt copy over is insane. 

Please fix this, and yes, the rest of the ui theme doesnt seem to work with the url thingy (popup?). And i suppose this is a way to transform it into a global search function? If so it looks very similar to the current firefox url suggestions popup, which was only meant to show suggestions, nothing more. Maybe it needs to be redesigned from the ground up  with columns when searching for bookmarks, history or chatGPT. You can integrate the library within this or add a side pane to preview bookmarks, history, passwords, AI conversations etc. This is a really good direction to go in, integrating multiple broken off components into one extremely powerful urlbar! I hope its going in a direction of becoming extremely useful instead of just staying as is

**Comment by prypyet** [comment]
I just realized this isn't a place for suggestions, my bad.

**Comment by arscynic** [comment]
Because I place the URL bar at the bottom, ~this silly update has rendered it impossible to see what I'm typing in there~ fixed.

**Comment by mr-cheffy** [comment]
https://www.reddit.com/r/zen_browser/s/MFfQKAdBj4

**Comment by prypyet** [comment]
the mod team here is so insanely quick, this is so nice to see!
