### ISSUE TITLE
"Zen Browser.app" is damaged and can't be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by marfrede** [zen-browser/desktop#371]
### What happened?

1. I am on Apple M1 Pro (macOS Sonoma Version `14.6.1`)
1. went to https://www.zen-browser.app/download in Google Chrome (Version 127.0.6533.120 (Official Build) (arm64))
1. chose `macos` -> `aarch64` and `Download 🥳`
1. downloaded and opened `zen.macos-aarch64.dmg`
1. moved `Zen Browser.app` to Applications
1. tryed to open it and got an error message:   ![Untitled](https://github.com/user-attachments/assets/a4a6fa50-4f7c-4c14-96b4-31d1d092a019)

![image](https://github.com/user-attachments/assets/d119fef5-2e0b-430a-8ea3-b2cd1a9f82a3)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by hkhrithik007** [comment]
just do 
xattr -c (drag app image from application )
run  this in terminal and zen will work

**Comment by mauro-balades** [comment]
Checkout pinned issues

**Comment by 0dragosh** [comment]
Just disabling Gatekeeper might be a good temporary solution, but there's other things that require notarization to work like the 1Password integration. When attempting to whitelist Zen it errors out due to it not being notarized.

<img width="319" alt="Screenshot 2024-08-21 at 09 46 00" src="https://github.com/user-attachments/assets/87c03e63-adfd-465b-8427-8075f48b381f">

**Comment by marfrede** [comment]
pinned issue: https://github.com/zen-browser/desktop/issues/53
