### ISSUE TITLE
cannot hit the close button

### ISSUE THREAD

**Issue by InvariantPause** [zen-browser/desktop#3803]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

i cannot hit the close unless and until i move thee cursor to the edge of the icon 
![Screenshot 2024-12-16 065934](https://github.com/user-attachments/assets/e926d81f-93b6-437d-b546-07a60b023f60) i literally have to press on the edge i would like to take this problem into account thanks.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Latest one

### What platform are you seeing the problem on?

Windows

**Comment by syscat29** [comment]
This happens because the toolbox occupies the full window height, so when it's moved to the right the following rule is applied.

```css
padding-top: var(--zen-toolbar-height);
```

This moves the items right below the window buttons but it means the toolbox is still being drawn above the buttons, replacing the padding with the following fixes the issue.

```css
margin-top: var(--zen-toolbar-height);
```

**Comment by mr-cheffy** [comment]
Thanks @j14i!

This will be fixed in the next release
