### ISSUE TITLE
Moving the sidebar to the right brings back the Top Bar

### ISSUE THREAD

**Issue by adam-devel** [zen-browser/desktop#3840]
### Captchas

- [X] I have read the instructions.
- [X] I am not filing an enhancement request.
- [X] I have searched existing issues and avoided creating duplicates.

### What happened?

When the tabs are moved to right side of the screen (by checking off the "Tabs on the right" option in the context menu). the top bar (which shouldn't appear) acts as if the browser is in compact mode: it peeks in when the mouse hovers close to it.

I reiterate, this ONLY happens when the the tabs are on the right side of the screen. other issues that only appear when tabs are on the right side: #3785 #3800. 

Note that the top bar is empty. presumably because all widgets are moved to the new side bar.

The following is a video demonstration of the issue:

https://github.com/user-attachments/assets/cfad2250-5d38-4096-99a0-e9063634320f

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 (Firefox 133.0.3)

### What platform are you seeing the problem on?

Linux

**Comment by far19a** [comment]
Not the developer but I think that's an expected behaviour. The purpose of why the top bar is hidden is to hide some unused top elements during single toolbar mode, typically bookmarks toolbar and system navigation button so it looks clean while still respecting system navigation placement.

Okay here you may not have bookmarks. But then, you may not noticed but, you have **_a close button_** on the left side. So Zen expects to keep the system navigation placement remains on the left while also keep its single toolbar design.

Unless like yeah you want the navigation button to be moved along to the right and left and ignore system navigation placement, making Zen close button on macOS on the right and ignore macOS navigation layout or put the close button on the left and ignore Windows navigation layout, which it'll be different from other apps and feels unusual to your muscle memory, sure. **_But not quite expected behaviour and may should not be a default action, aka. as an option._** It would feels a little janky. I don't think many apps ever disrespected system navigation placement ever bcs how weird it'll feel to its users and how it'll feels less native.

Or maybe a better approach is using smaller navigation bar for system navigation like full screen Windows games.

**Comment by adam-devel** [comment]
@far14c nope, this is an obvious bug. it's already a bug that the close button doesn't follow the sidebar. there's no technical limitations regarding the placement of the close button, it's rendered by zen not by the OS

**Comment by mr-cheffy** [comment]
We are following operating system standards, therefor, this is a feature. We are trying to keep the window elements always on the same position the OS tell us it's supposed to be. If your GTK enviroment tells us they should be on the left, they will always be on the left

**Comment by adam-devel** [comment]
> We are following operating system standards, therefor, this is a feature. We are trying to keep the window elements always on the same position the OS tell us it's supposed to be. If your GTK enviroment tells us they should be on the left, they will always be on the left

fine, you have to be able to acknowledge however that the chosen solution is just a hack. why bring back an entire bar for just one button ? make the close button a cutout or move it along with the sidebar and just keep it on the left side of the sidebar
