### ISSUE TITLE
Can't run it on On Apple M3 Sonoma 14

### ISSUE THREAD

**Issue by gaboesquivel** [zen-browser/desktop#405]
### What happened?

![image](https://github.com/user-attachments/assets/a6b33b11-5165-4c25-b07b-5fe7f6a763b0)

On Apple M3 Sonoma 14

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

alpha

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by aaftre** [comment]
M1 Sonoma Version 14.6.1 reporting in.

**Comment by mauro-balades** [comment]
Checkout https://github.com/zen-browser/desktop/issues/53

**Comment by Vashiru** [comment]
@mauro-balades May I suggest improving the banner on the download page? I mean it states follow the instructions but with the button being 'Download Zen Browser', I figured it was just a repeated download button or (due to the style and the page it's on) a donation button:

![image](https://github.com/user-attachments/assets/fa5ba7f3-26e5-4bbe-a660-60b5c8e44711)

Either way, the current banner doesn't have the UX that something is off / requires attention. I redownloaded the browser 3 times before searching for a ticket to know if I had to complain or not. What's also not helping is the guide just being named '[macOS] Install guide'. Perhaps '[macOS] Install guide - handling corrupt message' would be better.

The screenshots look amazing, I am looking forward to testing the browser, but am currently afraid a lot of people will give up due to these pains on Mac OS.
