### ISSUE TITLE
Split View hotkey seem not to behave as intendet

### ISSUE THREAD

**Issue by IZxMD** [zen-browser/desktop#425]
### What happened?

Like using hotkey to go into Split View Grid, and then using Horizontal seems to be not working as intendet, it goes ina 2x2 grid and loses every tab beside one.

https://github.com/user-attachments/assets/8740d575-41dd-4a60-ad91-badf866d501e

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed 👍🏽

**Comment by guigirl42** [comment]
> Fixed 👍🏽

Ooh, nice. Is it thus correct to presume that if you've now [8 hrs ago] marked this bug as being fixed, that we can assume it also applies to https://github.com/zen-browser/desktop/issues/341 ?

**Comment by mauro-balades** [comment]
yep, release is curently building so feel free to reopen if it persists https://github.com/zen-browser/desktop/actions/runs/10515786467

**Comment by guigirl42** [comment]
Don't wanna embarrass you, but geez you're excellent. Thanks for this browser gift to us. 

PS: I did not know that _we_ can Reopen, i thought that was only available to _you_ as the owner?

**Comment by mauro-balades** [comment]
> PS: I did not know that _we_ can Reopen, i thought that was only available to _you_ as the owner?

oh well, just ping me then and ill reopen 👍🏽

**Comment by guigirl42** [comment]
Sadly, still broken; same symptoms. :cry:

**Comment by mauro-balades** [comment]
> Sadly, still broken; same symptoms. 😢

What version?

**Comment by guigirl42** [comment]
Oh i'm so terribly sorry, what a dope i am for omitting that! I meant to include... it's your latest; 28.

**Comment by guigirl42** [comment]
I should mention ... _selfishly!_... that whilst my remarks apply to both of the "green" shortcuts, & the "yellow", the one i am most enthusiastic to have available is the Grid one, coz it's really common that i need to tile/split  3 - 8 tabs. 

![image](https://github.com/user-attachments/assets/7a5f2d65-b16d-4772-83c9-eadf7f262c66)

Also, re the current status of the shortcut for Vertical, sometimes this works fine, but other times it somehow picks a _different_ tab to the pair i have selected. 

Currently, when i try to use either the Grid or Horizontal options, 100% of the time Zen gives me two tabs split Vertically, instead. 

Finally, i should emphasise, the problem is exclusive to the keyboard shortcuts only. The behaviour is perfect & reliable when i use the RMB context-menu method.

**Comment by mauro-balades** [comment]
Yep yep yep, this is all fixed (hopefully). Sorry for the trouble!

**Comment by guigirl42** [comment]
I've just tested `1.0.0-a.29`. There is sad news, & great news! 

**Sad**:
The kb shortcuts for two tabs vertical & horizontal  _do_ invoke the split view interface, but _only one_ tab is shown. :exploding_head: 

**Great**:
The kb shortcut for grid split works beautifully, i'm so happy! :tada: :partying_face: :woman_dancing: 
I tested it with 4 & 6 tabs, & it reliably worked each time. Given the latest weirdness with H & V as above, i then also tested it just for 2 tabs, & it does work reliably for these, creating H side-by-side tabs, which if the user wants can then be converted to V via the UI icon in the url bar. 

Thank you Dev! :hugs:
