### ISSUE TITLE
Can't delete workspace

### ISSUE THREAD

**Issue by prey169** [zen-browser/desktop#468]
### What happened?

I have 2 workspaces - the Default one, and a second one.

When clicking delete workspace for the second workspace, it sets it as the active workspace but doesn't delete it. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.a.27-1

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by n1ghthouse** [comment]
Can attest to this problem.

**Comment by maks-bondarenko** [comment]
Same here, ubuntu 22.04

**Comment by mauro-balades** [comment]
what version are you on?

**Comment by maks-bondarenko** [comment]
> what version are you on?

1.0.0-a.27 (64-bit)

**Comment by prey169** [comment]
looks like 1.0.0-a.28 just fixed this - will close

**Comment by Sumea** [comment]
I accidentally created a new workspace by converting a folder, as I had not understood the feature. I wanted to restore it back as a folder/pinned tab, and delete the work space entirely since I need only one for my own use but there is two delete buttons when right clicking, other one is grayed out and other one does nothing. I can try to delete the work space through gui as much as I want but I cannot.
