### ISSUE TITLE
Vim Mode

### ISSUE THREAD

**Issue by seocamo** [zen-browser/desktop#488]
### What feature would you like to see?

vim motions layer that let you navigate with motions and vim modes like Qutebrowser, but unlike qutebrowser the webpage hotkeys is only working in a "hotkey mode" this will let you navigate ex. youtube without the hotkeys getting in the way.
a lot of firefox/qutebrowser would love this feature.

### What platform are you seeing the problem on?

Linux

### Additional context

see qutebrowser or Surfingkeys for firefox as good example, but they don't get the hotkey mode, so you need the mouse, the mode would make it keyboard only.

**Comment by natefabian18** [comment]
Not to derail the discussion but as Zen is built on top of Firefox I have been using the [tridactyl](https://github.com/tridactyl/tridactyl) extension for this kind of functionality and haven't encountered any problems with it and Zen.

**Comment by mauro-balades** [comment]
Sorry, but im not planning on adding this  in the future

**Comment by ghost** [comment]
I understand the issue was closed, but I was curious to the reasoning in case issues might be resolved in the future? It would be a unique selling point in my opinion since only niche browsers support Vim-like navigation. I assume it is the maintenance burden? if so would it be considerd if the project expanded in contributors?

Since the browser is focused on productivity, it makes sense to add this. I have used Vimium and am able to navigate my browser way more and have less strain on my wrists. I would urge you to try a extension like Vimium to see for yourself. Especially using 'f' to select a link is really nice, because you don't have to use your mouse. And you reduce the context-switching from mouse -> keyboard -> mouse etc.
