### ISSUE TITLE
Cant Import Bookmarks and Passwords in Arch Linux

### ISSUE THREAD

**Issue by KekmaTime** [zen-browser/desktop#502]
### What happened?

I was attempting to switch from Firefox to Zen. As part of the process, I decided to back up my bookmarks and passwords. However, when trying to open the default file explorer to select the backup location, it does not open as expected.

### Steps to reproduce:

Attempt to back up bookmarks and passwords in Firefox.
Try to open the default file explorer to select the backup location.

### Expected behavior:
The file explorer should open, allowing the selection of a backup location.

### Actual behavior:
The file explorer does not open.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.15

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by unkindypie** [comment]
Same issue on Arch. Can't import passwords from Vivaldi, but bookmarks are imported

**Comment by tonystdeng** [comment]
Same here also on arch, i could import the passwords though, just the bookmarks not showing after imported

update: it turns out that the bookmarks are stored but it's just not showing under the tabs, because it automaticly suggests the links when you type part of the link of one of the sites in your imported bookmarks,

**Comment by l3-h6** [comment]
This issue is still unresolved, i am having the same issue on Arch Linux

**Comment by misantroop** [comment]
Should be elevated. Alternatives to import passwords?

**Comment by HauntedKnives** [comment]
The issue is not only when trying to import passwords. The file handler doesn't open anywhere like when trying to download, upload, pressing Ctrl + O, etc.

**Comment by ghost** [comment]
I have simmilar issue installing from flatpak flathub

maybe i didn't installed it properly trough flatpak, maybe some permission issue i can see the error

im running hyprland and i don't have issue with xdg-desktop-portal, everything is working, and also when i try to use the pre-compiled version the file picker is working with no issue, the reason why i did not just use the pre-compiled version is because i tried to use flatpak as much as possible for GUI app.

    [2, Main Thread] WARNING: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop: 'glib warning', file /home/ubuntu/actions-runner/_work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:201
    
    (zen:2): Gdk-WARNING **: 20:29:06.122: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop

and here some flatpak info persmission i gave

    [Context]
    shared=network;ipc;
    sockets=x11;wayland;pulseaudio;session-bus;system-bus;fallback-x11;ssh-auth;pcsc;cups;inherit-wayland-socket;
    devices=dri;all;shm;input;
    features=bluetooth;
    filesystems=xdg-download;home;xdg-config/gtk-4.0:ro;xdg-config/gtk-3.0:ro;xdg-data/themes:ro;xdg-config/Kvantum:ro;xdg-data/fonts:ro;
    persistent=.zen;
    
    [Session Bus Policy]
    org.freedesktop.Flatpak=talk
    org.mpris.MediaPlayer2.firefox.*=own
    org.freedesktop.ScreenSaver=talk
    org.a11y.Bus=talk
    org.mozilla.zen.*=own
    org.freedesktop.FileManager1=talk
    
    [System Bus Policy]
    org.freedesktop.NetworkManager=talk
    
    [Environment]
    QT_STYLE_OVERRIDE=kvantum
    GTK_THEME=Colloid-Purple-Dark-Compact-Catppuccin
    GTK_PATH=/app/lib/gtkmodules
    MESA_SHADER_CACHE_DIR=/var/cache/mesa_shader_cache_db
    ELECTRON_OZONE_PLATFORM_HINT=auto
    QT_QPA_PLATFORM=wayland;xcb
