### ISSUE TITLE
Allow moving the URL / Address Bar to the side with vertical tabs

### ISSUE THREAD

**Issue by YousufSSyed** [zen-browser/desktop#538]
### What feature would you like to see?

I would like to have the entire browser UI on the side to save space and for aesthetics, sort of look like Arc browser. There should be an option, perhaps in the settings, to show the URL Bar and browser addons on the sidebar.

### What platform are you seeing the problem on?

macOS

**Comment by Moshyfawn** [comment]
In its current state, not being able to see the URL in the sidebar incentivises me to keep the toolbar at the top, because it's slightly more finicky to hover-open it to both see/copy the URL as well as interact with/open extension popovers _(which would actually be pretty neat to be able to "activate" through the URL bar, but that's a completely separate feature request)_.

I'd love to be able to get rid of the top toolbar for a cleaner look at some point 👀.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/803

 ~ This is an automatic operation to better enhancements requests organization.
