### ISSUE TITLE
Custom/re-random Fingerprints

### ISSUE THREAD

**Issue by Iquaridys** [zen-browser/desktop#546]
### What feature would you like to see?

Custom/re-random Fingerprints like [ixBrowser ](https://ixbrowser.com/en) have.

before we run the browser we can setting proxy and change fingerprints like:
Canvas,
WebGL ,
Timezone based on IP/proxy,
Language based on IP/proxy,
Location based on IP/proxy
and else.

without use add-ons/extension or way the browser can pass/have good trust score at [creepjs](https://abrahamjuliot.github.io/creepjs/)

### What platform are you seeing the problem on?

Windows

**Comment by gunir** [comment]
The issue is we can't have both speed and privacy, and Zen is private enough but not too private to reduce speed. The trade-off of having better privacy has always been worse speed, and I doubt the above browser is better than [Mullvad/Tor (ranked no.1)](https://www.privacyguides.org/en/desktop-browsers/#mullvad-browser) in terms of privacy.

Those should be optional on/off in Settings, if you're interested, create Pull Request for this feature.
