### ISSUE TITLE
[Windows] Portable version is not actually portable.

### ISSUE THREAD

**Issue by MaggotHATE** [zen-browser/desktop#563]
### What happened?

Portable version downloaded from the website still stores profile data at `\AppData\Local\zen`, which makes it not portable at all.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

129.0.2.3

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
No one said it was portable, it's a generic version, built so that it supports older CPUs.
 Sorry

**Comment by MaggotHATE** [comment]
@mauro-balades what are you even talking about? It's optimized, and it's clearly written `Portable`.

![image](https://github.com/user-attachments/assets/092d1a5f-dcd8-4bf5-977e-4e3592ee2117)

**Comment by mauro-balades** [comment]
Oh right, the package is portable but not the browser

**Comment by molio** [comment]
> @mauro-balades what are you even talking about? It's optimized, and it's clearly written `Portable`.
> 
> ![image](https://private-user-images.githubusercontent.com/3975259/361132218-092d1a5f-dcd8-4bf5-977e-4e3592ee2117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDYyNTAsIm5iZiI6MTcyNDUwNTk1MCwicGF0aCI6Ii8zOTc1MjU5LzM2MTEzMjIxOC0wOTJkMWE1Zi1kY2Q4LTRiZjUtOTc3ZS00ZTM1OTJlZTIxMTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjRUMTMyNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFjNDQ1NmYzZmFiNmU2OGJmOWIzNTIyYTE3ODdjN2NmMDUxNjBjNzZjMTc0OGY2NTU3Y2I0Y2VmN2QwZTE4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AADo1D7fsn5iFu3JfM5X_yo_Y5ouYy9pMzY_6BwIJEo)

the same opinion
If it is not portable after being so clearly stated, it is now a scam.
Firefox on Windows allows users to create a BAT file or specify a profile location with startup options and use multiple profiles by itself at the same time.
It can be called portable only if it can go this far.
I think we should follow the same way.

[https://wiki.mozilla.org/Firefox/CommandLineOptions](url)

example

> @echo off
> 
> SET BASE=%~dp0
> 
> SET MOZ_NO_REMOTE=true
> start "firefoxPortable" %BASE%\firefox.exe -no-remote -profile "ptbl_01_profile_hoge" %1

**Comment by mauro-balades** [comment]
It's not a scam, portable means that it can be moved, that's why the zip is called portable. It doesn't mean that it won't create a profile directory

**Comment by molio** [comment]
> It's not a scam, portable means that it can be moved, that's why the zip is called portable. It doesn't mean that it won't create a profile directory

Copy that.

To the definition of the wordI'm not interested in defining words.
I am not interested in defining words.

I will not use the word portable thereafter.


Let the user create a profile in the directory of his/her choice, and have multiple profiles up and running and in use at the same time,
In other words, I want you to be able to do the same thing that firefox allows you to do.
This is a request.
Since it is a fork of firefox, it should follow the useful features of firefox.

**Comment by mauro-balades** [comment]
Your suggestion is to just create a profile in a different directory? That's what you are doing

**Comment by MaggotHATE** [comment]
> in a different directory

Not just in a different directory - in a directory **relative to the .exe**. This would allow to move this browser bewteen different machines (on an external drive, usb flash, etc). Firefox and its derivatives are better at it since profile data is not tied to a machine -  chromiums will remove passwords and history even on portable installations.

**Comment by molio** [comment]
> Your suggestion is to just create a profile in a different directory? That's what you are doing

Rather, it is this way.

USER have multiple profiles up and running and in use at the same time,

https://wiki.mozilla.org/Firefox/CommandLineOptions#User_profile

> 

    @echo off

    SET BASE=%~dp0

    SET MOZ_NO_REMOTE=true
    start "ZenPortable" %BASE%\Zen.exe -no-remote -profile "zen_test" %1

I just tried the above command line, and it seems that a profile folder named zen_test is created in the same directory as zen.exe and uses that profile.


Please do not remove this from your code in the future.
However, it seems that user.js, userchrome.css , userchrome.js , toolbar.uc.js that firefox user volunteers have prepared for customization cannot be used.

I think this is inevitable because zen has originally played with the UI, such as vertical tabs.

**Comment by MonolithOrchids** [comment]
@mauro-balades why is this issue closed?
Don't get me wrong, Zen is amazing, but the portable version on the website is clearly deceiving, I’ve never seen any other developer before using the word Portable to say "portable means the files can be moved" but when you move it, it can't be used because your profile doesn't move with it since it is not actually portable, so what’s the point here of this current “portable” version?!
At least leave a message/warning on the website about this, because this is clearly not portable at current state.

**Comment by Jobima1st** [comment]
> @mauro-balades why is this issue closed? Don't get me wrong, Zen is amazing, but the portable version on the website is clearly deceiving, I’ve never seen any other developer before using the word Portable to say "portable means the files can be moved" but when you move it, it can't be used because your profile doesn't move with it since it is not actually portable, so what’s the point here of this current “portable” version?! At least leave a message/warning on the website about this, because this is clearly not portable at current state.

see here https://github.com/zen-browser/desktop/discussions/804

**Comment by MonolithOrchids** [comment]
> see here #804

Fair, but still doesn't make any sense in having a "portable" version in your website, yet asking for a portable site to make a portable version of your project.
Like I said, at least a warning to people would be nice, because at this moment is very deceiving, me and many others (from this issue alone) fell for that "fake" portable version.

**Comment by kouiketsu** [comment]
Zen is also a Firefox browser, so you can still use Firefox's coding methods. However, you need to rename zen.exe to firefox.exe, then use the bat file provided in the link below and follow the instructions in the readme file. I have successfully made Zen portable, and all data is stored in the Profiles folder in the parent directory. Even if you move the directory, the data will not change, so you can safely copy it to a USB device.

Translated with [DeepL.com]

**Comment by kouiketsu** [comment]
链接：https://sourceforge.net/projects/libportable/files/
