### ISSUE TITLE
Vertical tab bar in compact mode does not appear when hovered (unmaximized)

### ISSUE THREAD

**Issue by siestamode** [zen-browser/desktop#58]
Environment: Windows 11, 1920x1080 resolution

Maximized result (expected result):
![image](https://github.com/user-attachments/assets/a9796870-4bac-41c6-9df1-d0b2e0d769f3)

Unmaximized result (actual result):
![image](https://github.com/user-attachments/assets/512cce62-e475-4b33-be40-b5114bc3d1bc)

Only in compact mode since vertical tab bar does not auto-hide

**Comment by NOCanoa** [comment]
When in full screen there are no tabs shown:
![image](https://github.com/user-attachments/assets/b5752744-1a28-4bfc-818a-2eff9c24e50e)
because when switching you see them moving up off screen, and if i use compact mode i can trigger the sideber in the top corner:
![image](https://github.com/user-attachments/assets/4e4be56d-fc1e-4ead-8493-75dbdf077e6b)

win 11 3840 x 2160px

**Comment by mauro-balades** [comment]
With in https://github.com/zen-browser/desktop/commit/bcb3a88d1679e92a2c64bd747159a58cc98fb42c thanks!
