### ISSUE TITLE
Translucent background from welcome page looks obfusticated

### ISSUE THREAD

**Issue by NaufilAsar** [zen-browser/desktop#589]
### What happened?

Hi, I just tried out using Zen browser on my Arch Linux with i3wm and picom. The welcome page looks different from macos:

![image](https://github.com/user-attachments/assets/3f782385-01ec-4ff6-ae5d-61063afb5e34)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.a.28-2

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by ghost** [comment]
I could be wrong but I'll wager this is because picom doesn't do 32bit depth. Most things with certain alpha's require 32bit compostion but picom only does a 24bit depth render. This means Terms with alpha end up adding it to your fonts/text rather than just backgrounds etc. Correct me if I'm wrong and how to get things to work because this has been a small picom saga for years with me.

xwininfo -root | grep Depth (if you get 24...well there you go)

Fire up a kitchen sink DE like Gnome/KDE/XFCE with a integrated compositor and run the same command, you get 32 and the alpha will work.
