### ISSUE TITLE
RSS feed reader + What is the Scope of Zen Browser?

### ISSUE THREAD

**Issue by gBasil** [zen-browser/desktop#677]
### What feature would you like to see?

One neat feature that Vivaldi has is a [feed reader](https://vivaldi.com/features/feed-reader). It implements feed auto-discovery and shows a little feed button in the URL bar if a feed is detected on the page, and also has a built-in feed reader directly in the browser. Even though I said "RSS" in the title, this feature would ideally also support Atom and JSON feeds.

### Other details

I'd also like to ask: what is the scope of Zen Browser? What features should/can be requested? A built-in feed reader is a pretty atypical feature present only in Vivaldi (from my knowledge), and it has proved immensely practical for me (though it could do with some love, it using the mail interface feels quite clunky). Would that be something this project would like to implement?

**Comment by guigirl42** [comment]
> could use second opinions

Fwiw, as a longterm Vivaldi user since its beginning, who lost faith in the project more recently, i have no interest nor desire at all for Zen [nor Floorp] to incorporate email & calendaring into it. Instead, Zen [& Floorp] would benefit [in this ardent user's mind, anyway] from the Dev/s' creative energies focusing on IMO vital issues like full _native_ `Sidebery` capability, & [in the case of Zen] expanded sophistication for the `Web Panel` functionality. As for a native RSS capability, that would be lovely too, but ONLY if doing so did _not_ then need doing a "full Vivaldi".

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/769

 ~ This is an automatic operation to better enhancements requests organization.
