### ISSUE TITLE
nix flake support?

### ISSUE THREAD

**Issue by dennkaii** [zen-browser/desktop#78]
**Is your feature request related to a problem? Please describe.**
I tried installing it but i cant because of nixos rn i dont remember which was the complain but is something related to nix.

**Describe the solution you'd like**
a nix flake or upload to nixkpgs repo
.
**Describe alternatives you've considered**
i considered packaging it myself but im not good enough. I will try again but if someone is more versed in packaging it i would appreciate the help,

**Additional context**

**Comment by mauro-balades** [comment]
Would you rather prefer a flatpak?

**Comment by mauro-balades** [comment]
We don't have any official nix support currently and we are not planning on having one, however, we do have a flatpak that should support it. I hope you understand, thanks!

**Comment by Eveeifyeve** [comment]
It's basically impossible even if you got it to build you would have to build it using the nix systems. Since you can't specifiy a libclang path

**Comment by Archisman-Mridha** [comment]
Publish Zen Browser to Nix packages will be so nice!

**Comment by eveeifyeve** [comment]
> Publish Zen Browser to Nix packages will be so nice!

Yes that would be nice, however It is not going to happen for security reasons due to the fact that there is only one core maintainer @mr-cheffy and that I will admit [didn't know how firefox releases worked back in alpha which does say a lot about security of a browser.](https://github.com/NixOS/nixpkgs/pull/363992#issuecomment-2564387704) So with those two reasons, till there is at least 2-3 maintainers actively working on zen-browser, It's just too much of a security risk to put in nixpkgs. Which you will clearly understand if you ever done security against browsers in open-source repositories.

**Comment by mr-cheffy** [comment]
> I will admit https://github.com/NixOS/nixpkgs/pull/363992#issuecomment-2564387704 So with those two reasons, till there is at least 2-3 maintainers actively working on zen-browser, It's just too much of a security risk to put in nixpkgs. Which you will clearly understand if you ever done security against browsers in open-source repositories.

Those things wheren't a priority in alpha (which was around 2 years ago when zen just launched and was just a toy project), but as you can see now, zen consistently provides the security updates it needs within the time range.

But I dont care what you want or say, I just want you to please stop pinging me if you aren't directly requiring my attention. I had to say this 4 times already to you specifically.

**Comment by eveeifyeve** [comment]
> > I will admit [NixOS/nixpkgs#363992 (comment)](https://github.com/NixOS/nixpkgs/pull/363992#issuecomment-2564387704) So with those two reasons, till there is at least 2-3 maintainers actively working on zen-browser, It's just too much of a security risk to put in nixpkgs. Which you will clearly understand if you ever done security against browsers in open-source repositories.
> 
> Those things wheren't a priority in alpha (which was around 2 years ago when zen just launched and was just a toy project), but as you can see now, zen consistently provides the security updates it needs within the time range.

This issue has been present for around two years and, in my view, should have been treated as a higher priority due to its potential security implications. Since you are currently the sole maintainer of zen-browser, delays in addressing it could really impact users who are using nixpkgs. With unofficial branches/user provided flakes/nur, users generally understand there may be security risks. However, in nixpkgs—as the official package repository—there is a higher expectation that widely used packages, such as browsers, that should meet stronger security standards.

For more context, Emily has outlined the concern details here: https://github.com/NixOS/nixpkgs/pull/363992#pullrequestreview-2523997020

> But I dont care what you want or say, I just want you to please stop pinging me if you aren't directly requiring my attention. I had to say this 4 times already to you specifically.

I was replying to a comment outside my PR and mentioned you because you are the listed maintainer. If that is an issue, you may want to adjust your notification settings.

Also, this is the first time you have asked me to stop, so I was not made aware that it was a concern.

**Comment by mr-cheffy** [comment]
Straight up lying now? https://github.com/NixOS/nixpkgs/pull/363992#issuecomment-2960823772

**Comment by eveeifyeve** [comment]
> Straight up lying now? [NixOS/nixpkgs#363992 (comment)](https://github.com/NixOS/nixpkgs/pull/363992#issuecomment-2960823772)

No, not at all. I still have interest to doing that pr, however the concerns that you have mentioned in that pr are still existent doesn't matter if it's been a couple of months since this browser done security updates. The problem is we are not accepting a browser that is not considered stable yet, because that could mean there is potential security implications for users if a firefox update gets delayed. It would also be good to have a second maintainer to make sure that security is actually taken seriously instead of what happened in alpha that delayed security Firefox updates to users, therefore in nixpkgs, we couldn't follow our policy of update zen-browser that has the newer version of firefox in 72 hours or less.

**Comment by mr-cheffy** [comment]
Sorry but that just seems like a dumb rationale, but sure, do whatever you want I don't really care. If anyone's wondering, you can install it at https://github.com/0xc000022070/zen-browser-flake
