### ISSUE TITLE
better and more beautiful new tab

### ISSUE THREAD

**Issue by mauro-balades** [zen-browser/desktop#8]

**Comment by bdbch** [comment]
Just make sure to keep it minimal. I like Brave but I always hate to setup a new Brave browser because of all that random stuff on the New Tab page.

I think an minimal, good looking page with a search bar is fine. Then give users options to toggle most viewed pages, custom pinned pages, background images, etc.

**Comment by axel37** [comment]
I love the way Vivaldi does it :

- Search bar
- List of bookmarks and folders shown in a grid
  - Elements can be re-arranged by drag-and-drop (including placing them inside folders)
  - Middle-clicking on a folder opens all its contained bookmarks in new tabs

It makes the home page actually useful and provides a great way to navigate bookmarks.
