### ISSUE TITLE
[Feature] remember and switch to last opened tab when switching workspaces

### ISSUE THREAD

**Issue by that-ambuj** [zen-browser/desktop#979]
### What happened?

When I switch from one workspace to the other, it goes back to the first tab instead of the one that was last opened in that workspace. 

I like to quickly switch between workspaces for work and reading documentations, I would like that it remembers where I left off in every workspace. We could make it an option in the settings and keep it enabled by default.

PS: I would like to contribute in building this feature!

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Low

### What platform are you seeing the problem on?

Linux, Windows

**Comment by lubdhak7414** [comment]
Same, just moved from Arc. This is very annoying.

**Comment by ma77hiaz** [comment]
+1

**Comment by BrhmDev** [comment]
This has been implemented in the current version.

**Comment by EnzoPV25** [comment]
Hi,

I'm testing Zen and having the same issue. It's a fresh install, on version 1.0.1-a.22 and if I have a pinned tab open in workspace A, switch to workspace B and come back to workspace A, it just open a new tab instead of keeping me on my lastest opened tab.

This is pretty annoying because I like to switch a lot between my different workspace when working.

**Comment by Eejit43** [comment]
I am experiencing the same issue on the same version, but only with regards to pinned tabs, not normal tabs.
