### ISSUE TITLE
Sidebar overflows to the right when in compact mode and "Tabs on the right" is checked

### ISSUE THREAD

**Issue by yashptel** [zen-browser/desktop#989]
### What happened?

![image](https://github.com/user-attachments/assets/3cf52370-f57e-4998-9924-8ff2d4c531cc)

- Sidebar overflows out of the screen to the right when in compact mode and "Tabs on the right" is checked. Looks like position issue most likely

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.31

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by lbrdt** [comment]
still persists on a.34

**Comment by Nirose** [comment]
If anyone's having this problem. A temporary fix is to copy all content of (to make it easy) `zen-compact-mode.css` from [here](https://github.com/zen-browser/desktop/blob/00fb5c24f97668c5fdad0626c8fe93d402d88e3e/src/browser/base/content/zen-styles/zen-compact-mode.css) to your Zen browser profiles' `chrome` folder and rename it to `userChrome.css`.

![image](https://github.com/user-attachments/assets/e4dfbb8b-95ab-4fe9-93bd-c67a102c0dbc)

Then on line `178` increase the `right` value to fit your need.

So for me:

`right: 0 !important;`

became

`right: 55px !important;`

Then restart the browser. 

Result:

![image](https://github.com/user-attachments/assets/9274db94-2e98-4590-b3f1-6d4f845a2286)



There's a little wonky flicker because there's also a scrollbar on the right and mouse will hover over the scroll bar at times, and the tabs disappear. Other than that, it works fine, for me at least. Hopefully this helps
